In [0]:
# Change directory to VSCode workspace root so that relative path loads work correctly. Turn this addition off with the DataScience.changeDirOnImportExport setting
import os
try:
	os.chdir(os.path.join(os.getcwd(), '..'))
	print(os.getcwd())
except:
	pass

 # Nomenclature of territorial units for statistics (NUTS)

In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# set jupyter notebook display options
pd.set_option('display.max_rows', 500) # set up display area to show dataframe
pd.options.display.max_rows # prevent truncation of text strings in columns
pd.set_option('display.max_colwidth', -1)

In [3]:
# read csv files with NUTS data
nuts = pd.read_csv('data/NUTS/NUTS_AT_2016.csv')
nuts.dtypes # return columns and their datatypes

CNTR_CODE    object
NUTS_ID      object
NUTS_NAME    object
dtype: object

 ## North Sea region

In [4]:
# filter for the North Sea region (BE, DE, DK, FR, NL, NO, SE, UK)
nuts = nuts.drop(nuts[~((nuts.CNTR_CODE=='BE')|(nuts.CNTR_CODE=='DE')|(nuts.CNTR_CODE=='DK')|(nuts.CNTR_CODE=='FR')|(nuts.CNTR_CODE=='NL')|(nuts.CNTR_CODE=='NO')|(nuts.CNTR_CODE=='SE')|(nuts.CNTR_CODE=='UK'))].index)

In [5]:
# sort values by NUTS_ID
nuts = nuts.sort_values(['NUTS_ID'])

In [6]:
# countries (NUTS 0) - code has two characters
nuts0 = nuts.loc[nuts['NUTS_ID'].str.len()==2].copy()
nuts0 = nuts0.reset_index(drop=True) # reset index
nuts0

  CNTR_CODE NUTS_ID         NUTS_NAME
0  BE        BE      BELGIQUE-BELGIË
1  DE        DE      DEUTSCHLAND
2  DK        DK      DANMARK
3  FR        FR      FRANCE
4  NL        NL      NEDERLAND
5  NO        NO      NORGE
6  SE        SE      SVERIGE
7  UK        UK      UNITED KINGDOM

In [7]:
# NUTS 1 - code has three characters
nuts1 = nuts.loc[nuts['NUTS_ID'].str.len()==3].copy()

In [8]:
# NUTS 2 - code has four characters
nuts2 = nuts.loc[nuts['NUTS_ID'].str.len()==4].copy()

In [9]:
# NUTS 3 - code has five characters
nuts3 = nuts.loc[nuts['NUTS_ID'].str.len()==5].copy()

 ## North Sea region - by country

 ### Belgium

In [10]:
# filter for BE
be = nuts.loc[nuts['CNTR_CODE']=='BE'].copy()

In [11]:
# NUTS 1
be_nuts1 = be.loc[nuts['NUTS_ID'].str.len()==3].copy()
be_nuts1 = be_nuts1.reset_index(drop=True) # reset index
be_nuts1

,CNTR_CODE,NUTS_ID,NUTS_NAME
0,BE,BE1,RÉGION DE BRUXELLES-CAPITALE/BRUSSELS HOOFDSTEDELIJK GEWEST
1,BE,BE2,VLAAMS GEWEST
2,BE,BE3,RÉGION WALLONNE

In [12]:
# NUTS 2
be_nuts2 = be.loc[nuts['NUTS_ID'].str.len()==4].copy()
be_nuts2 = be_nuts2.reset_index(drop=True) # reset index
be_nuts2

,CNTR_CODE,NUTS_ID,NUTS_NAME
0,BE,BE10,Région de Bruxelles-Capitale/ Brussels Hoofdstedelijk Gewest
1,BE,BE21,Prov. Antwerpen
2,BE,BE22,Prov. Limburg (BE)
3,BE,BE23,Prov. Oost-Vlaanderen
4,BE,BE24,Prov. Vlaams-Brabant
5,BE,BE25,Prov. West-Vlaanderen
6,BE,BE31,Prov. Brabant Wallon
7,BE,BE32,Prov. Hainaut
8,BE,BE33,Prov. Liège
9,BE,BE34,Prov. Luxembourg (BE)
10,BE,BE35,Prov. Namur

In [13]:
# NUTS 3
be_nuts3 = be.loc[nuts['NUTS_ID'].str.len()==5].copy()
be_nuts3 = be_nuts3.reset_index(drop=True) # reset index
be_nuts3

   CNTR_CODE NUTS_ID                                              NUTS_NAME
0   BE        BE100   Arr. de Bruxelles-Capitale/Arr. van Brussel-Hoofdstad
1   BE        BE211   Arr. Antwerpen
2   BE        BE212   Arr. Mechelen
3   BE        BE213   Arr. Turnhout
4   BE        BE221   Arr. Hasselt
5   BE        BE222   Arr. Maaseik
6   BE        BE223   Arr. Tongeren
7   BE        BE231   Arr. Aalst
8   BE        BE232   Arr. Dendermonde
9   BE        BE233   Arr. Eeklo
10  BE        BE234   Arr. Gent
11  BE        BE235   Arr. Oudenaarde
12  BE        BE236   Arr. Sint-Niklaas
13  BE        BE241   Arr. Halle-Vilvoorde
14  BE        BE242   Arr. Leuven
15  BE        BE251   Arr. Brugge
16  BE        BE252   Arr. Diksmuide
17  BE        BE253   Arr. Ieper
18  BE        BE254   Arr. Kortrijk
19  BE        BE255   Arr. Oostende
20  BE        BE256   Arr. Roeselare
21  BE        BE257   Arr. Tielt
22  BE        BE258   Arr. Veurne
23  BE        BE310   Arr. Nivelles
24  BE        BE321   Arr. Ath
25  BE        BE322   Arr. Charleroi
26  BE        BE323   Arr. Mons
27  BE        BE324   Arr. Mouscron
28  BE        BE325   Arr. Soignies
29  BE        BE326   Arr. Thuin
30  BE        BE327   Arr. Tournai
31  BE        BE331   Arr. Huy
32  BE        BE332   Arr. Liège
33  BE        BE334   Arr. Waremme
34  BE        BE335   Arr. Verviers - communes francophones
35  BE        BE336   Bezirk Verviers - Deutschsprachige Gemeinschaft
36  BE        BE341   Arr. Arlon
37  BE        BE342   Arr. Bastogne
38  BE        BE343   Arr. Marche-en-Famenne
39  BE        BE344   Arr. Neufchâteau
40  BE        BE345   Arr. Virton
41  BE        BE351   Arr. Dinant
42  BE        BE352   Arr. Namur
43  BE        BE353   Arr. Philippeville

 ### Germany

In [14]:
# filter for DE
de = nuts.loc[nuts['CNTR_CODE']=='DE'].copy()

In [15]:
# NUTS 1
de_nuts1 = de.loc[nuts['NUTS_ID'].str.len()==3].copy()
de_nuts1 = de_nuts1.reset_index(drop=True) # reset index
de_nuts1

   CNTR_CODE NUTS_ID               NUTS_NAME
0   DE        DE1     BADEN-WÜRTTEMBERG
1   DE        DE2     BAYERN
2   DE        DE3     BERLIN
3   DE        DE4     BRANDENBURG
4   DE        DE5     BREMEN
5   DE        DE6     HAMBURG
6   DE        DE7     HESSEN
7   DE        DE8     MECKLENBURG-VORPOMMERN
8   DE        DE9     NIEDERSACHSEN
9   DE        DEA     NORDRHEIN-WESTFALEN
10  DE        DEB     RHEINLAND-PFALZ
11  DE        DEC     SAARLAND
12  DE        DED     SACHSEN
13  DE        DEE     SACHSEN-ANHALT
14  DE        DEF     SCHLESWIG-HOLSTEIN
15  DE        DEG     THÜRINGEN

In [16]:
# NUTS 2
de_nuts2 = de.loc[nuts['NUTS_ID'].str.len()==4].copy()
de_nuts2 = de_nuts2.reset_index(drop=True) # reset index
de_nuts2

   CNTR_CODE NUTS_ID               NUTS_NAME
0   DE        DE11    Stuttgart
1   DE        DE12    Karlsruhe
2   DE        DE13    Freiburg
3   DE        DE14    Tübingen
4   DE        DE21    Oberbayern
5   DE        DE22    Niederbayern
6   DE        DE23    Oberpfalz
7   DE        DE24    Oberfranken
8   DE        DE25    Mittelfranken
9   DE        DE26    Unterfranken
10  DE        DE27    Schwaben
11  DE        DE30    Berlin
12  DE        DE40    Brandenburg
13  DE        DE50    Bremen
14  DE        DE60    Hamburg
15  DE        DE71    Darmstadt
16  DE        DE72    Gießen
17  DE        DE73    Kassel
18  DE        DE80    Mecklenburg-Vorpommern
19  DE        DE91    Braunschweig
20  DE        DE92    Hannover
21  DE        DE93    Lüneburg
22  DE        DE94    Weser-Ems
23  DE        DEA1    Düsseldorf
24  DE        DEA2    Köln
25  DE        DEA3    Münster
26  DE        DEA4    Detmold
27  DE        DEA5    Arnsberg
28  DE        DEB1    Koblenz
29  DE        DEB2    Trier
30  DE        DEB3    Rheinhessen-Pfalz
31  DE        DEC0    Saarland
32  DE        DED2    Dresden
33  DE        DED4    Chemnitz
34  DE        DED5    Leipzig
35  DE        DEE0    Sachsen-Anhalt
36  DE        DEF0    Schleswig-Holstein
37  DE        DEG0    Thüringen

In [17]:
# NUTS 3
de_nuts3 = de.loc[nuts['NUTS_ID'].str.len()==5].copy()
de_nuts3 = de_nuts3.reset_index(drop=True) # reset index
de_nuts3

    CNTR_CODE NUTS_ID                                     NUTS_NAME
0    DE        DE111   Stuttgart, Stadtkreis
1    DE        DE112   Böblingen
2    DE        DE113   Esslingen
3    DE        DE114   Göppingen
4    DE        DE115   Ludwigsburg
5    DE        DE116   Rems-Murr-Kreis
6    DE        DE117   Heilbronn, Stadtkreis
7    DE        DE118   Heilbronn, Landkreis
8    DE        DE119   Hohenlohekreis
9    DE        DE11A   Schwäbisch Hall
10   DE        DE11B   Main-Tauber-Kreis
11   DE        DE11C   Heidenheim
12   DE        DE11D   Ostalbkreis
13   DE        DE121   Baden-Baden, Stadtkreis
14   DE        DE122   Karlsruhe, Stadtkreis
15   DE        DE123   Karlsruhe, Landkreis
16   DE        DE124   Rastatt
17   DE        DE125   Heidelberg, Stadtkreis
18   DE        DE126   Mannheim, Stadtkreis
19   DE        DE127   Neckar-Odenwald-Kreis
20   DE        DE128   Rhein-Neckar-Kreis
21   DE        DE129   Pforzheim, Stadtkreis
22   DE        DE12A   Calw
23   DE        DE12B   Enzkreis
24   DE        DE12C   Freudenstadt
25   DE        DE131   Freiburg im Breisgau, Stadtkreis
26   DE        DE132   Breisgau-Hochschwarzwald
27   DE        DE133   Emmendingen
28   DE        DE134   Ortenaukreis
29   DE        DE135   Rottweil
30   DE        DE136   Schwarzwald-Baar-Kreis
31   DE        DE137   Tuttlingen
32   DE        DE138   Konstanz
33   DE        DE139   Lörrach
34   DE        DE13A   Waldshut
35   DE        DE141   Reutlingen
36   DE        DE142   Tübingen, Landkreis
37   DE        DE143   Zollernalbkreis
38   DE        DE144   Ulm, Stadtkreis
39   DE        DE145   Alb-Donau-Kreis
40   DE        DE146   Biberach
41   DE        DE147   Bodenseekreis
42   DE        DE148   Ravensburg
43   DE        DE149   Sigmaringen
44   DE        DE211   Ingolstadt, Kreisfreie Stadt
45   DE        DE212   München, Kreisfreie Stadt
46   DE        DE213   Rosenheim, Kreisfreie Stadt
47   DE        DE214   Altötting
48   DE        DE215   Berchtesgadener Land
49   DE        DE216   Bad Tölz-Wolfratshausen
50   DE        DE217   Dachau
51   DE        DE218   Ebersberg
52   DE        DE219   Eichstätt
53   DE        DE21A   Erding
54   DE        DE21B   Freising
55   DE        DE21C   Fürstenfeldbruck
56   DE        DE21D   Garmisch-Partenkirchen
57   DE        DE21E   Landsberg am Lech
58   DE        DE21F   Miesbach
59   DE        DE21G   Mühldorf a. Inn
60   DE        DE21H   München, Landkreis
61   DE        DE21I   Neuburg-Schrobenhausen
62   DE        DE21J   Pfaffenhofen a. d. Ilm
63   DE        DE21K   Rosenheim, Landkreis
64   DE        DE21L   Starnberg
65   DE        DE21M   Traunstein
66   DE        DE21N   Weilheim-Schongau
67   DE        DE221   Landshut, Kreisfreie Stadt
68   DE        DE222   Passau, Kreisfreie Stadt
69   DE        DE223   Straubing, Kreisfreie Stadt
70   DE        DE224   Deggendorf
71   DE        DE225   Freyung-Grafenau
72   DE        DE226   Kelheim
73   DE        DE227   Landshut, Landkreis
74   DE        DE228   Passau, Landkreis
75   DE        DE229   Regen
76   DE        DE22A   Rottal-Inn
77   DE        DE22B   Straubing-Bogen
78   DE        DE22C   Dingolfing-Landau
79   DE        DE231   Amberg, Kreisfreie Stadt
80   DE        DE232   Regensburg, Kreisfreie Stadt
81   DE        DE233   Weiden i. d. Opf, Kreisfreie Stadt
82   DE        DE234   Amberg-Sulzbach
83   DE        DE235   Cham
84   DE        DE236   Neumarkt i. d. OPf.
85   DE        DE237   Neustadt a. d. Waldnaab
86   DE        DE238   Regensburg, Landkreis
87   DE        DE239   Schwandorf
88   DE        DE23A   Tirschenreuth
89   DE        DE241   Bamberg, Kreisfreie Stadt
90   DE        DE242   Bayreuth, Kreisfreie Stadt
91   DE        DE243   Coburg, Kreisfreie Stadt
92   DE        DE244   Hof, Kreisfreie Stadt
93   DE        DE245   Bamberg, Landkreis
94   DE        DE246   Bayreuth, Landkreis
95   DE        DE247   Coburg, Landkreis
96   DE        DE248   Forchheim
97   DE        DE249   Hof, Landkreis
98   DE        DE24A   Kronach
99   DE        DE24B   Kulmbach
100  DE        DE24C   Lichtenfels
101  DE        DE24D   Wunsiedel i. Fichtelgebirge
102  DE        DE251   Ansbach, Kreisfreie Stadt
103  DE        DE252   Erlangen, Kreisfreie Stadt
104  DE        DE253   Fürth, Kreisfreie Stadt
105  DE        DE254   Nürnberg, Kreisfreie Stadt
106  DE        DE255   Schwabach, Kreisfreie Stadt
107  DE        DE256   Ansbach, Landkreis
108  DE        DE257   Erlangen-Höchstadt
109  DE        DE258   Fürth, Landkreis
110  DE        DE259   Nürnberger Land
111  DE        DE25A   Neustadt a. d. Aisch-Bad Windsheim
112  DE        DE25B   Roth
113  DE        DE25C   Weißenburg-Gunzenhausen
114  DE        DE261   Aschaffenburg, Kreisfreie Stadt
115  DE        DE262   Schweinfurt, Kreisfreie Stadt
116  DE        DE263   Würzburg, Kreisfreie Stadt
117  DE        DE264   Aschaffenburg, Landkreis
118  DE        DE265   Bad Kissingen
119  DE        DE266   Rhön-Grabfeld
120  DE        DE267   Haßberge
121  DE        DE268   Kitzingen
122  DE        DE269   Miltenberg
123  DE        DE26A   Main-Spessart
124  DE        DE26B   Schweinfurt, Landkreis
125  DE        DE26C   Würzburg, Landkreis
126  DE        DE271   Augsburg, Kreisfreie Stadt
127  DE        DE272   Kaufbeuren, Kreisfreie Stadt
128  DE        DE273   Kempten (Allgäu), Kreisfreie Stadt
129  DE        DE274   Memmingen, Kreisfreie Stadt
130  DE        DE275   Aichach-Friedberg
131  DE        DE276   Augsburg, Landkreis
132  DE        DE277   Dillingen a.d. Donau
133  DE        DE278   Günzburg
134  DE        DE279   Neu-Ulm
135  DE        DE27A   Lindau (Bodensee)
136  DE        DE27B   Ostallgäu
137  DE        DE27C   Unterallgäu
138  DE        DE27D   Donau-Ries
139  DE        DE27E   Oberallgäu
140  DE        DE300   Berlin
141  DE        DE401   Brandenburg an der Havel, Kreisfreie Stadt
142  DE        DE402   Cottbus, Kreisfreie Stadt
143  DE        DE403   Frankfurt (Oder), Kreisfreie Stadt
144  DE        DE404   Potsdam, Kreisfreie Stadt
145  DE        DE405   Barnim
146  DE        DE406   Dahme-Spreewald
147  DE        DE407   Elbe-Elster
148  DE        DE408   Havelland
149  DE        DE409   Märkisch-Oderland
150  DE        DE40A   Oberhavel
151  DE        DE40B   Oberspreewald-Lausitz
152  DE        DE40C   Oder-Spree
153  DE        DE40D   Ostprignitz-Ruppin
154  DE        DE40E   Potsdam-Mittelmark
155  DE        DE40F   Prignitz
156  DE        DE40G   Spree-Neiße
157  DE        DE40H   Teltow-Fläming
158  DE        DE40I   Uckermark
159  DE        DE501   Bremen, Kreisfreie Stadt
160  DE        DE502   Bremerhaven, Kreisfreie Stadt
161  DE        DE600   Hamburg
162  DE        DE711   Darmstadt, Kreisfreie Stadt
163  DE        DE712   Frankfurt am Main, Kreisfreie Stadt
164  DE        DE713   Offenbach am Main, Kreisfreie Stadt
165  DE        DE714   Wiesbaden, Kreisfreie Stadt
166  DE        DE715   Bergstraße
167  DE        DE716   Darmstadt-Dieburg
168  DE        DE717   Groß-Gerau
169  DE        DE718   Hochtaunuskreis
170  DE        DE719   Main-Kinzig-Kreis
171  DE        DE71A   Main-Taunus-Kreis
172  DE        DE71B   Odenwaldkreis
173  DE        DE71C   Offenbach, Landkreis
174  DE        DE71D   Rheingau-Taunus-Kreis
175  DE        DE71E   Wetteraukreis
176  DE        DE721   Gießen, Landkreis
177  DE        DE722   Lahn-Dill-Kreis
178  DE        DE723   Limburg-Weilburg
179  DE        DE724   Marburg-Biedenkopf
180  DE        DE725   Vogelsbergkreis
181  DE        DE731   Kassel, Kreisfreie Stadt
182  DE        DE732   Fulda
183  DE        DE733   Hersfeld-Rotenburg
184  DE        DE734   Kassel, Landkreis
185  DE        DE735   Schwalm-Eder-Kreis
186  DE        DE736   Waldeck-Frankenberg
187  DE        DE737   Werra-Meißner-Kreis
188  DE        DE803   Rostock, Kreisfreie Stadt
189  DE        DE804   Schwerin, Kreisfreie Stadt
190  DE        DE80J   Mecklenburgische Seenplatte
191  DE        DE80K   Landkreis Rostock
192  DE        DE80L   Vorpommern-Rügen
193  DE        DE80M   Nordwestmecklenburg
194  DE        DE80N   Vorpommern-Greifswald
195  DE        DE80O   Ludwigslust-Parchim
196  DE        DE911   Braunschweig, Kreisfreie Stadt
197  DE        DE912   Salzgitter, Kreisfreie Stadt
198  DE        DE913   Wolfsburg, Kreisfreie Stadt
199  DE        DE914   Gifhorn
200  DE        DE916   Goslar
201  DE        DE917   Helmstedt
202  DE        DE918   Northeim
203  DE        DE91A   Peine
204  DE        DE91B   Wolfenbüttel
205  DE        DE91C   Göttingen
206  DE        DE922   Diepholz
207  DE        DE923   Hameln-Pyrmont
208  DE        DE925   Hildesheim
209  DE        DE926   Holzminden
210  DE        DE927   Nienburg (Weser)
211  DE        DE928   Schaumburg
212  DE        DE929   Region Hannover
213  DE        DE931   Celle
214  DE        DE932   Cuxhaven
215  DE        DE933   Harburg
216  DE        DE934   Lüchow-Dannenberg
217  DE        DE935   Lüneburg, Landkreis
218  DE        DE936   Osterholz
219  DE        DE937   Rotenburg (Wümme)
220  DE        DE938   Heidekreis
221  DE        DE939   Stade
222  DE        DE93A   Uelzen
223  DE        DE93B   Verden
224  DE        DE941   Delmenhorst, Kreisfreie Stadt
225  DE        DE942   Emden, Kreisfreie Stadt
226  DE        DE943   Oldenburg (Oldenburg), Kreisfreie Stadt
227  DE        DE944   Osnabrück, Kreisfreie Stadt
228  DE        DE945   Wilhelmshaven, Kreisfreie Stadt
229  DE        DE946   Ammerland
230  DE        DE947   Aurich
231  DE        DE948   Cloppenburg
232  DE        DE949   Emsland
233  DE        DE94A   Friesland (DE)
234  DE        DE94B   Grafschaft Bentheim
235  DE        DE94C   Leer
236  DE        DE94D   Oldenburg, Landkreis
237  DE        DE94E   Osnabrück, Landkreis
238  DE        DE94F   Vechta
239  DE        DE94G   Wesermarsch
240  DE        DE94H   Wittmund
241  DE        DEA11   Düsseldorf, Kreisfreie Stadt
242  DE        DEA12   Duisburg, Kreisfreie Stadt
243  DE        DEA13   Essen, Kreisfreie Stadt
244  DE        DEA14   Krefeld, Kreisfreie Stadt
245  DE        DEA15   Mönchengladbach, Kreisfreie Stadt
246  DE        DEA16   Mülheim an der Ruhr, Kreisfreie Stadt
247  DE        DEA17   Oberhausen, Kreisfreie Stadt
248  DE        DEA18   Remscheid, Kreisfreie Stadt
249  DE        DEA19   Solingen, Kreisfreie Stadt
250  DE        DEA1A   Wuppertal, Kreisfreie Stadt
251  DE        DEA1B   Kleve
252  DE        DEA1C   Mettmann
253  DE        DEA1D   Rhein-Kreis Neuss
254  DE        DEA1E   Viersen
255  DE        DEA1F   Wesel
256  DE        DEA22   Bonn, Kreisfreie Stadt
257  DE        DEA23   Köln, Kreisfreie Stadt
258  DE        DEA24   Leverkusen, Kreisfreie Stadt
259  DE        DEA26   Düren
260  DE        DEA27   Rhein-Erft-Kreis
261  DE        DEA28   Euskirchen
262  DE        DEA29   Heinsberg
263  DE        DEA2A   Oberbergischer Kreis
264  DE        DEA2B   Rheinisch-Bergischer Kreis
265  DE        DEA2C   Rhein-Sieg-Kreis
266  DE        DEA2D   Städteregion Aachen
267  DE        DEA31   Bottrop, Kreisfreie Stadt
268  DE        DEA32   Gelsenkirchen, Kreisfreie Stadt
269  DE        DEA33   Münster, Kreisfreie Stadt
270  DE        DEA34   Borken
271  DE        DEA35   Coesfeld
272  DE        DEA36   Recklinghausen
273  DE        DEA37   Steinfurt
274  DE        DEA38   Warendorf
275  DE        DEA41   Bielefeld, Kreisfreie Stadt
276  DE        DEA42   Gütersloh
277  DE        DEA43   Herford
278  DE        DEA44   Höxter
279  DE        DEA45   Lippe
280  DE        DEA46   Minden-Lübbecke
281  DE        DEA47   Paderborn
282  DE        DEA51   Bochum, Kreisfreie Stadt
283  DE        DEA52   Dortmund, Kreisfreie Stadt
284  DE        DEA53   Hagen, Kreisfreie Stadt
285  DE        DEA54   Hamm, Kreisfreie Stadt
286  DE        DEA55   Herne, Kreisfreie Stadt
287  DE        DEA56   Ennepe-Ruhr-Kreis
288  DE        DEA57   Hochsauerlandkreis
289  DE        DEA58   Märkischer Kreis
290  DE        DEA59   Olpe
291  DE        DEA5A   Siegen-Wittgenstein
292  DE        DEA5B   Soest
293  DE        DEA5C   Unna
294  DE        DEB11   Koblenz, Kreisfreie Stadt
295  DE        DEB12   Ahrweiler
296  DE        DEB13   Altenkirchen (Westerwald)
297  DE        DEB14   Bad Kreuznach
298  DE        DEB15   Birkenfeld
299  DE        DEB17   Mayen-Koblenz
300  DE        DEB18   Neuwied
301  DE        DEB1A   Rhein-Lahn-Kreis
302  DE        DEB1B   Westerwaldkreis
303  DE        DEB1C   Cochem-Zell
304  DE        DEB1D   Rhein-Hunsrück-Kreis
305  DE        DEB21   Trier, Kreisfreie Stadt
306  DE        DEB22   Bernkastel-Wittlich
307  DE        DEB23   Eifelkreis Bitburg-Prüm
308  DE        DEB24   Vulkaneifel
309  DE        DEB25   Trier-Saarburg
310  DE        DEB31   Frankenthal (Pfalz), Kreisfreie Stadt
311  DE        DEB32   Kaiserslautern, Kreisfreie Stadt
312  DE        DEB33   Landau in der Pfalz, Kreisfreie Stadt
313  DE        DEB34   Ludwigshafen am Rhein, Kreisfreie Stadt
314  DE        DEB35   Mainz, Kreisfreie Stadt
315  DE        DEB36   Neustadt an der Weinstraße, Kreisfreie Stadt
316  DE        DEB37   Pirmasens, Kreisfreie Stadt
317  DE        DEB38   Speyer, Kreisfreie Stadt
318  DE        DEB39   Worms, Kreisfreie Stadt
319  DE        DEB3A   Zweibrücken, Kreisfreie Stadt
320  DE        DEB3B   Alzey-Worms
321  DE        DEB3C   Bad Dürkheim
322  DE        DEB3D   Donnersbergkreis
323  DE        DEB3E   Germersheim
324  DE        DEB3F   Kaiserslautern, Landkreis
325  DE        DEB3G   Kusel
326  DE        DEB3H   Südliche Weinstraße
327  DE        DEB3I   Rhein-Pfalz-Kreis
328  DE        DEB3J   Mainz-Bingen
329  DE        DEB3K   Südwestpfalz
330  DE        DEC01   Regionalverband Saarbrücken
331  DE        DEC02   Merzig-Wadern
332  DE        DEC03   Neunkirchen
333  DE        DEC04   Saarlouis
334  DE        DEC05   Saarpfalz-Kreis
335  DE        DEC06   St. Wendel
336  DE        DED21   Dresden, Kreisfreie Stadt
337  DE        DED2C   Bautzen
338  DE        DED2D   Görlitz
339  DE        DED2E   Meißen
340  DE        DED2F   Sächsische Schweiz-Osterzgebirge
341  DE        DED41   Chemnitz, Kreisfreie Stadt
342  DE        DED42   Erzgebirgskreis
343  DE        DED43   Mittelsachsen
344  DE        DED44   Vogtlandkreis
345  DE        DED45   Zwickau
346  DE        DED51   Leipzig, Kreisfreie Stadt
347  DE        DED52   Leipzig
348  DE        DED53   Nordsachsen
349  DE        DEE01   Dessau-Roßlau, Kreisfreie Stadt
350  DE        DEE02   Halle (Saale), Kreisfreie Stadt
351  DE        DEE03   Magdeburg, Kreisfreie Stadt
352  DE        DEE04   Altmarkkreis Salzwedel
353  DE        DEE05   Anhalt-Bitterfeld
354  DE        DEE06   Jerichower Land
355  DE        DEE07   Börde
356  DE        DEE08   Burgenlandkreis
357  DE        DEE09   Harz
358  DE        DEE0A   Mansfeld-Südharz
359  DE        DEE0B   Saalekreis
360  DE        DEE0C   Salzlandkreis
361  DE        DEE0D   Stendal
362  DE        DEE0E   Wittenberg
363  DE        DEF01   Flensburg, Kreisfreie Stadt
364  DE        DEF02   Kiel, Kreisfreie Stadt
365  DE        DEF03   Lübeck, Kreisfreie Stadt
366  DE        DEF04   Neumünster, Kreisfreie Stadt
367  DE        DEF05   Dithmarschen
368  DE        DEF06   Herzogtum Lauenburg
369  DE        DEF07   Nordfriesland
370  DE        DEF08   Ostholstein
371  DE        DEF09   Pinneberg
372  DE        DEF0A   Plön
373  DE        DEF0B   Rendsburg-Eckernförde
374  DE        DEF0C   Schleswig-Flensburg
375  DE        DEF0D   Segeberg
376  DE        DEF0E   Steinburg
377  DE        DEF0F   Stormarn
378  DE        DEG01   Erfurt, Kreisfreie Stadt
379  DE        DEG02   Gera, Kreisfreie Stadt
380  DE        DEG03   Jena, Kreisfreie Stadt
381  DE        DEG04   Suhl, Kreisfreie Stadt
382  DE        DEG05   Weimar, Kreisfreie Stadt
383  DE        DEG06   Eichsfeld
384  DE        DEG07   Nordhausen
385  DE        DEG09   Unstrut-Hainich-Kreis
386  DE        DEG0A   Kyffhäuserkreis
387  DE        DEG0B   Schmalkalden-Meiningen
388  DE        DEG0C   Gotha
389  DE        DEG0D   Sömmerda
390  DE        DEG0E   Hildburghausen
391  DE        DEG0F   Ilm-Kreis
392  DE        DEG0G   Weimarer Land
393  DE        DEG0H   Sonneberg
394  DE        DEG0I   Saalfeld-Rudolstadt
395  DE        DEG0J   Saale-Holzland-Kreis
396  DE        DEG0K   Saale-Orla-Kreis
397  DE        DEG0L   Greiz
398  DE        DEG0M   Altenburger Land
399  DE        DEG0N   Eisenach, Kreisfreie Stadt
400  DE        DEG0P   Wartburgkreis

 ### Denmark

In [18]:
# filter for DK
dk = nuts.loc[nuts['CNTR_CODE']=='DK'].copy()

In [19]:
# NUTS 1
dk_nuts1 = dk.loc[nuts['NUTS_ID'].str.len()==3].copy()
dk_nuts1 = dk_nuts1.reset_index(drop=True) # reset index
dk_nuts1

  CNTR_CODE NUTS_ID NUTS_NAME
0  DK        DK0     DANMARK

In [20]:
# NUTS 2
dk_nuts2 = dk.loc[nuts['NUTS_ID'].str.len()==4].copy()
dk_nuts2 = dk_nuts2.reset_index(drop=True) # reset index
dk_nuts2

  CNTR_CODE NUTS_ID    NUTS_NAME
0  DK        DK01    Hovedstaden
1  DK        DK02    Sjælland
2  DK        DK03    Syddanmark
3  DK        DK04    Midtjylland
4  DK        DK05    Nordjylland

In [21]:
# NUTS 3
dk_nuts3 = dk.loc[nuts['NUTS_ID'].str.len()==5].copy()
dk_nuts3 = dk_nuts3.reset_index(drop=True) # reset index
dk_nuts3

   CNTR_CODE NUTS_ID             NUTS_NAME
0   DK        DK011   Byen København
1   DK        DK012   Københavns omegn
2   DK        DK013   Nordsjælland
3   DK        DK014   Bornholm
4   DK        DK021   Østsjælland
5   DK        DK022   Vest- og Sydsjælland
6   DK        DK031   Fyn
7   DK        DK032   Sydjylland
8   DK        DK041   Vestjylland
9   DK        DK042   Østjylland
10  DK        DK050   Nordjylland

 ### France

In [22]:
# filter for FR
fr = nuts.loc[nuts['CNTR_CODE']=='FR'].copy()

In [23]:
# NUTS 1
fr_nuts1 = fr.loc[nuts['NUTS_ID'].str.len()==3].copy()
fr_nuts1 = fr_nuts1.reset_index(drop=True) # reset index
fr_nuts1

   CNTR_CODE NUTS_ID                                       NUTS_NAME
0   FR        FR1     ILE-DE-FRANCE
1   FR        FRB     CENTRE - VAL DE LOIRE
2   FR        FRC     BOURGOGNE-FRANCHE-COMTÉ
3   FR        FRD     NORMANDIE
4   FR        FRE     NORD-PAS DE CALAIS-PICARDIE
5   FR        FRF     ALSACE-CHAMPAGNE-ARDENNE-LORRAINE
6   FR        FRG     PAYS DE LA LOIRE
7   FR        FRH     BRETAGNE
8   FR        FRI     AQUITAINE-LIMOUSIN-POITOU-CHARENTES
9   FR        FRJ     LANGUEDOC-ROUSSILLON-MIDI-PYRÉNÉES
10  FR        FRK     AUVERGNE-RHÔNE-ALPES
11  FR        FRL     PROVENCE-ALPES-CÔTE D’AZUR
12  FR        FRM     CORSE
13  FR        FRY     RUP FR - RÉGIONS ULTRAPÉRIPHÉRIQUES FRANÇAISES

In [24]:
# drop entries corresponding to "RUP FR - RÉGIONS ULTRAPÉRIPHÉRIQUES FRANÇAISES" (FRY) - French Overseas Territories
fr = fr[~fr.NUTS_ID.str.contains("FRY")]
nuts = nuts[~nuts.NUTS_ID.str.contains("FRY")]
nuts2 = nuts2[~nuts2.NUTS_ID.str.contains("FRY")]
nuts3 = nuts3[~nuts3.NUTS_ID.str.contains("FRY")]
fr_nuts1 = fr_nuts1[~fr_nuts1.NUTS_ID.str.contains("FRY")]

In [25]:
# NUTS 2
fr_nuts2 = fr.loc[nuts['NUTS_ID'].str.len()==4].copy()
fr_nuts2 = fr_nuts2.reset_index(drop=True) # reset index
fr_nuts2

   CNTR_CODE NUTS_ID                   NUTS_NAME
0   FR        FR10    Ile-de-France
1   FR        FRB0    Centre - Val de Loire
2   FR        FRC1    Bourgogne
3   FR        FRC2    Franche-Comté
4   FR        FRD1    Basse-Normandie
5   FR        FRD2    Haute-Normandie
6   FR        FRE1    Nord-Pas de Calais
7   FR        FRE2    Picardie
8   FR        FRF1    Alsace
9   FR        FRF2    Champagne-Ardenne
10  FR        FRF3    Lorraine
11  FR        FRG0    Pays de la Loire
12  FR        FRH0    Bretagne
13  FR        FRI1    Aquitaine
14  FR        FRI2    Limousin
15  FR        FRI3    Poitou-Charentes
16  FR        FRJ1    Languedoc-Roussillon
17  FR        FRJ2    Midi-Pyrénées
18  FR        FRK1    Auvergne
19  FR        FRK2    Rhône-Alpes
20  FR        FRL0    Provence-Alpes-Côte d’Azur
21  FR        FRM0    Corse

In [26]:
# NUTS 3
fr_nuts3 = fr.loc[nuts['NUTS_ID'].str.len()==5].copy()
fr_nuts3 = fr_nuts3.reset_index(drop=True) # reset index
fr_nuts3

   CNTR_CODE NUTS_ID                NUTS_NAME
0   FR        FR101   Paris
1   FR        FR102   Seine-et-Marne
2   FR        FR103   Yvelines
3   FR        FR104   Essonne
4   FR        FR105   Hauts-de-Seine
5   FR        FR106   Seine-Saint-Denis
6   FR        FR107   Val-de-Marne
7   FR        FR108   Val-d'Oise
8   FR        FRB01   Cher
9   FR        FRB02   Eure-et-Loir
10  FR        FRB03   Indre
11  FR        FRB04   Indre-et-Loire
12  FR        FRB05   Loir-et-Cher
13  FR        FRB06   Loiret
14  FR        FRC11   Côte-d’Or
15  FR        FRC12   Nièvre
16  FR        FRC13   Saône-et-Loire
17  FR        FRC14   Yonne
18  FR        FRC21   Doubs
19  FR        FRC22   Jura
20  FR        FRC23   Haute-Saône
21  FR        FRC24   Territoire de Belfort
22  FR        FRD11   Calvados
23  FR        FRD12   Manche
24  FR        FRD13   Orne
25  FR        FRD21   Eure
26  FR        FRD22   Seine-Maritime
27  FR        FRE11   Nord
28  FR        FRE12   Pas-de-Calais
29  FR        FRE21   Aisne
30  FR        FRE22   Oise
31  FR        FRE23   Somme
32  FR        FRF11   Bas-Rhin
33  FR        FRF12   Haut-Rhin
34  FR        FRF21   Ardennes
35  FR        FRF22   Aube
36  FR        FRF23   Marne
37  FR        FRF24   Haute-Marne
38  FR        FRF31   Meurthe-et-Moselle
39  FR        FRF32   Meuse
40  FR        FRF33   Moselle
41  FR        FRF34   Vosges
42  FR        FRG01   Loire-Atlantique
43  FR        FRG02   Maine-et-Loire
44  FR        FRG03   Mayenne
45  FR        FRG04   Sarthe
46  FR        FRG05   Vendée
47  FR        FRH01   Côtes-d’Armor
48  FR        FRH02   Finistère
49  FR        FRH03   Ille-et-Vilaine
50  FR        FRH04   Morbihan
51  FR        FRI11   Dordogne
52  FR        FRI12   Gironde
53  FR        FRI13   Landes
54  FR        FRI14   Lot-et-Garonne
55  FR        FRI15   Pyrénées-Atlantiques
56  FR        FRI21   Corrèze
57  FR        FRI22   Creuse
58  FR        FRI23   Haute-Vienne
59  FR        FRI31   Charente
60  FR        FRI32   Charente-Maritime
61  FR        FRI33   Deux-Sèvres
62  FR        FRI34   Vienne
63  FR        FRJ11   Aude
64  FR        FRJ12   Gard
65  FR        FRJ13   Hérault
66  FR        FRJ14   Lozère
67  FR        FRJ15   Pyrénées-Orientales
68  FR        FRJ21   Ariège
69  FR        FRJ22   Aveyron
70  FR        FRJ23   Haute-Garonne
71  FR        FRJ24   Gers
72  FR        FRJ25   Lot
73  FR        FRJ26   Hautes-Pyrénées
74  FR        FRJ27   Tarn
75  FR        FRJ28   Tarn-et-Garonne
76  FR        FRK11   Allier
77  FR        FRK12   Cantal
78  FR        FRK13   Haute-Loire
79  FR        FRK14   Puy-de-Dôme
80  FR        FRK21   Ain
81  FR        FRK22   Ardèche
82  FR        FRK23   Drôme
83  FR        FRK24   Isère
84  FR        FRK25   Loire
85  FR        FRK26   Rhône
86  FR        FRK27   Savoie
87  FR        FRK28   Haute-Savoie
88  FR        FRL01   Alpes-de-Haute-Provence
89  FR        FRL02   Hautes-Alpes
90  FR        FRL03   Alpes-Maritimes
91  FR        FRL04   Bouches-du-Rhône
92  FR        FRL05   Var
93  FR        FRL06   Vaucluse
94  FR        FRM01   Corse-du-Sud
95  FR        FRM02   Haute-Corse

 ### Netherlands

In [27]:
# filter for NL
nl = nuts.loc[nuts['CNTR_CODE']=='NL'].copy()

In [28]:
# NUTS 1
nl_nuts1 = nl.loc[nuts['NUTS_ID'].str.len()==3].copy()
nl_nuts1 = nl_nuts1.reset_index(drop=True) # reset index
nl_nuts1

  CNTR_CODE NUTS_ID        NUTS_NAME
0  NL        NL1     NOORD-NEDERLAND
1  NL        NL2     OOST-NEDERLAND
2  NL        NL3     WEST-NEDERLAND
3  NL        NL4     ZUID-NEDERLAND

In [29]:
# NUTS 2
nl_nuts2 = nl.loc[nuts['NUTS_ID'].str.len()==4].copy()
nl_nuts2 = nl_nuts2.reset_index(drop=True) # reset index
nl_nuts2

   CNTR_CODE NUTS_ID       NUTS_NAME
0   NL        NL11    Groningen
1   NL        NL12    Friesland (NL)
2   NL        NL13    Drenthe
3   NL        NL21    Overijssel
4   NL        NL22    Gelderland
5   NL        NL23    Flevoland
6   NL        NL31    Utrecht
7   NL        NL32    Noord-Holland
8   NL        NL33    Zuid-Holland
9   NL        NL34    Zeeland
10  NL        NL41    Noord-Brabant
11  NL        NL42    Limburg (NL)

In [30]:
# NUTS 3
nl_nuts3 = nl.loc[nuts['NUTS_ID'].str.len()==5].copy()
nl_nuts3 = nl_nuts3.reset_index(drop=True) # reset index
nl_nuts3

   CNTR_CODE NUTS_ID                            NUTS_NAME
0   NL        NL111   Oost-Groningen
1   NL        NL112   Delfzijl en omgeving
2   NL        NL113   Overig Groningen
3   NL        NL124   Noord-Friesland
4   NL        NL125   Zuidwest-Friesland
5   NL        NL126   Zuidoost-Friesland
6   NL        NL131   Noord-Drenthe
7   NL        NL132   Zuidoost-Drenthe
8   NL        NL133   Zuidwest-Drenthe
9   NL        NL211   Noord-Overijssel
10  NL        NL212   Zuidwest-Overijssel
11  NL        NL213   Twente
12  NL        NL221   Veluwe
13  NL        NL224   Zuidwest-Gelderland
14  NL        NL225   Achterhoek
15  NL        NL226   Arnhem/Nijmegen
16  NL        NL230   Flevoland
17  NL        NL310   Utrecht
18  NL        NL321   Kop van Noord-Holland
19  NL        NL323   IJmond
20  NL        NL324   Agglomeratie Haarlem
21  NL        NL325   Zaanstreek
22  NL        NL327   Het Gooi en Vechtstreek
23  NL        NL328   Alkmaar en omgeving
24  NL        NL329   Groot-Amsterdam
25  NL        NL332   Agglomeratie's-Gravenhage
26  NL        NL333   Delft en Westland
27  NL        NL337   Agglomeratie Leiden en Bollenstreek
28  NL        NL33A   Zuidoost-Zuid-Holland
29  NL        NL33B   Oost-Zuid-Holland
30  NL        NL33C   Groot-Rijnmond
31  NL        NL341   Zeeuwsch-Vlaanderen
32  NL        NL342   Overig Zeeland
33  NL        NL411   West-Noord-Brabant
34  NL        NL412   Midden-Noord-Brabant
35  NL        NL413   Noordoost-Noord-Brabant
36  NL        NL414   Zuidoost-Noord-Brabant
37  NL        NL421   Noord-Limburg
38  NL        NL422   Midden-Limburg
39  NL        NL423   Zuid-Limburg

 ### Norway

In [31]:
# filter for NO
no = nuts.loc[nuts['CNTR_CODE']=='NO'].copy()

In [32]:
# NUTS 1
no_nuts1 = no.loc[nuts['NUTS_ID'].str.len()==3].copy()
no_nuts1 = no_nuts1.reset_index(drop=True) # reset index
no_nuts1

  CNTR_CODE NUTS_ID NUTS_NAME
0  NO        NO0     NORGE

In [33]:
# NUTS 2
no_nuts2 = no.loc[nuts['NUTS_ID'].str.len()==4].copy()
no_nuts2 = no_nuts2.reset_index(drop=True) # reset index
no_nuts2

  CNTR_CODE NUTS_ID           NUTS_NAME
0  NO        NO01    Oslo og Akershus
1  NO        NO02    Hedmark og Oppland
2  NO        NO03    Sør-Østlandet
3  NO        NO04    Agder og Rogaland
4  NO        NO05    Vestlandet
5  NO        NO06    Trøndelag
6  NO        NO07    Nord-Norge

In [34]:
# NUTS 3
no_nuts3 = no.loc[nuts['NUTS_ID'].str.len()==5].copy()
no_nuts3 = no_nuts3.reset_index(drop=True) # reset index
no_nuts3

   CNTR_CODE NUTS_ID         NUTS_NAME
0   NO        NO011   Oslo
1   NO        NO012   Akershus
2   NO        NO021   Hedmark
3   NO        NO022   Oppland
4   NO        NO031   Østfold
5   NO        NO032   Buskerud
6   NO        NO033   Vestfold
7   NO        NO034   Telemark
8   NO        NO041   Aust-Agder
9   NO        NO042   Vest-Agder
10  NO        NO043   Rogaland
11  NO        NO051   Hordaland
12  NO        NO052   Sogn og Fjordane
13  NO        NO053   Møre og Romsdal
14  NO        NO060   Trøndelag
15  NO        NO071   Nordland
16  NO        NO072   Troms
17  NO        NO073   Finnmark

 ### Sweden

In [35]:
# filter for SE
se = nuts.loc[nuts['CNTR_CODE']=='SE'].copy()

In [36]:
# NUTS 1
se_nuts1 = se.loc[nuts['NUTS_ID'].str.len()==3].copy()
se_nuts1 = se_nuts1.reset_index(drop=True) # reset index
se_nuts1

  CNTR_CODE NUTS_ID      NUTS_NAME
0  SE        SE1     ÖSTRA SVERIGE
1  SE        SE2     SÖDRA SVERIGE
2  SE        SE3     NORRA SVERIGE

In [37]:
# NUTS 2
se_nuts2 = se.loc[nuts['NUTS_ID'].str.len()==4].copy()
se_nuts2 = se_nuts2.reset_index(drop=True) # reset index
se_nuts2

  CNTR_CODE NUTS_ID            NUTS_NAME
0  SE        SE11    Stockholm
1  SE        SE12    Östra Mellansverige
2  SE        SE21    Småland med öarna
3  SE        SE22    Sydsverige
4  SE        SE23    Västsverige
5  SE        SE31    Norra Mellansverige
6  SE        SE32    Mellersta Norrland
7  SE        SE33    Övre Norrland

In [38]:
# NUTS 3
se_nuts3 = se.loc[nuts['NUTS_ID'].str.len()==5].copy()
se_nuts3 = se_nuts3.reset_index(drop=True) # reset index
se_nuts3

   CNTR_CODE NUTS_ID             NUTS_NAME
0   SE        SE110   Stockholms län
1   SE        SE121   Uppsala län
2   SE        SE122   Södermanlands län
3   SE        SE123   Östergötlands län
4   SE        SE124   Örebro län
5   SE        SE125   Västmanlands län
6   SE        SE211   Jönköpings län
7   SE        SE212   Kronobergs län
8   SE        SE213   Kalmar län
9   SE        SE214   Gotlands län
10  SE        SE221   Blekinge län
11  SE        SE224   Skåne län
12  SE        SE231   Hallands län
13  SE        SE232   Västra Götalands län
14  SE        SE311   Värmlands län
15  SE        SE312   Dalarnas län
16  SE        SE313   Gävleborgs län
17  SE        SE321   Västernorrlands län
18  SE        SE322   Jämtlands län
19  SE        SE331   Västerbottens län
20  SE        SE332   Norrbottens län

 ### United Kingdom

In [39]:
# filter for UK
uk = nuts.loc[nuts['CNTR_CODE']=='UK'].copy()

In [40]:
# NUTS 1
uk_nuts1 = uk.loc[nuts['NUTS_ID'].str.len()==3].copy()
uk_nuts1 = uk_nuts1.reset_index(drop=True) # reset index
uk_nuts1

   CNTR_CODE NUTS_ID                 NUTS_NAME
0   UK        UKC     NORTH EAST (ENGLAND)
1   UK        UKD     NORTH WEST (ENGLAND)
2   UK        UKE     YORKSHIRE AND THE HUMBER
3   UK        UKF     EAST MIDLANDS (ENGLAND)
4   UK        UKG     WEST MIDLANDS (ENGLAND)
5   UK        UKH     EAST OF ENGLAND
6   UK        UKI     LONDON
7   UK        UKJ     SOUTH EAST (ENGLAND)
8   UK        UKK     SOUTH WEST (ENGLAND)
9   UK        UKL     WALES
10  UK        UKM     SCOTLAND
11  UK        UKN     NORTHERN IRELAND

In [41]:
# NUTS 2
uk_nuts2 = uk.loc[nuts['NUTS_ID'].str.len()==4].copy()
uk_nuts2 = uk_nuts2.reset_index(drop=True) # reset index
uk_nuts2

   CNTR_CODE NUTS_ID                                         NUTS_NAME
0   UK        UKC1    Tees Valley and Durham
1   UK        UKC2    Northumberland and Tyne and Wear
2   UK        UKD1    Cumbria
3   UK        UKD3    Greater Manchester
4   UK        UKD4    Lancashire
5   UK        UKD6    Cheshire
6   UK        UKD7    Merseyside
7   UK        UKE1    East Yorkshire and Northern Lincolnshire
8   UK        UKE2    North Yorkshire
9   UK        UKE3    South Yorkshire
10  UK        UKE4    West Yorkshire
11  UK        UKF1    Derbyshire and Nottinghamshire
12  UK        UKF2    Leicestershire, Rutland and Northamptonshire
13  UK        UKF3    Lincolnshire
14  UK        UKG1    Herefordshire, Worcestershire and Warwickshire
15  UK        UKG2    Shropshire and Staffordshire
16  UK        UKG3    West Midlands
17  UK        UKH1    East Anglia
18  UK        UKH2    Bedfordshire and Hertfordshire
19  UK        UKH3    Essex
20  UK        UKI3    Inner London - West
21  UK        UKI4    Inner London - East
22  UK        UKI5    Outer London - East and North East
23  UK        UKI6    Outer London - South
24  UK        UKI7    Outer London - West and North West
25  UK        UKJ1    Berkshire, Buckinghamshire and Oxfordshire
26  UK        UKJ2    Surrey, East and West Sussex
27  UK        UKJ3    Hampshire and Isle of Wight
28  UK        UKJ4    Kent
29  UK        UKK1    Gloucestershire, Wiltshire and Bristol/Bath area
30  UK        UKK2    Dorset and Somerset
31  UK        UKK3    Cornwall and Isles of Scilly
32  UK        UKK4    Devon
33  UK        UKL1    West Wales and The Valleys
34  UK        UKL2    East Wales
35  UK        UKM5    North Eastern Scotland
36  UK        UKM6    Highlands and Islands
37  UK        UKM7    Eastern Scotland
38  UK        UKM8    West Central Scotland
39  UK        UKM9    Southern Scotland
40  UK        UKN0    Northern Ireland

In [42]:
# NUTS 3
uk_nuts3 = uk.loc[nuts['NUTS_ID'].str.len()==5].copy()
uk_nuts3 = uk_nuts3.reset_index(drop=True) # reset index
uk_nuts3

,CNTR_CODE,NUTS_ID,NUTS_NAME
0,UK,UKC11,Hartlepool and Stockton-on-Tees
1,UK,UKC12,South Teesside
2,UK,UKC13,Darlington
3,UK,UKC14,Durham CC
4,UK,UKC21,Northumberland
5,UK,UKC22,Tyneside
6,UK,UKC23,Sunderland
7,UK,UKD11,West Cumbria
8,UK,UKD12,East Cumbria
9,UK,UKD33,Manchester
10,UK,UKD34,Greater Manchester South West
11,UK,UKD35,Greater Manchester South East
12,UK,UKD36,Greater Manchester North West
13,UK,UKD37,Greater Manchester North East
14,UK,UKD41,Blackburn with Darwen
15,UK,UKD42,Blackpool
16,UK,UKD44,Lancaster and Wyre
17,UK,UKD45,Mid Lancashire
18,UK,UKD46,East Lancashire
19,UK,UKD47,Chorley and West Lancashire
20,UK,UKD61,Warrington
21,UK,UKD62,Cheshire East
22,UK,UKD63,Cheshire West and Chester
23,UK,UKD71,East Merseyside
24,UK,UKD72,Liverpool
25,UK,UKD73,Sefton
26,UK,UKD74,Wirral
27,UK,UKE11,"Kingston upon Hull, City of"
28,UK,UKE12,East Riding of Yorkshire
29,UK,UKE13,North and North East Lincolnshire
30,UK,UKE21,York
31,UK,UKE22,North Yorkshire CC
32,UK,UKE31,"Barnsley, Doncaster and Rotherham"
33,UK,UKE32,Sheffield
34,UK,UKE41,Bradford
35,UK,UKE42,Leeds
36,UK,UKE44,Calderdale and Kirklees
37,UK,UKE45,Wakefield
38,UK,UKF11,Derby
39,UK,UKF12,East Derbyshire
40,UK,UKF13,South and West Derbyshire
41,UK,UKF14,Nottingham
42,UK,UKF15,North Nottinghamshire
43,UK,UKF16,South Nottinghamshire
44,UK,UKF21,Leicester
45,UK,UKF22,Leicestershire CC and Rutland
46,UK,UKF24,West Northamptonshire
47,UK,UKF25,North Northamptonshire
48,UK,UKF30,Lincolnshire
49,UK,UKG11,"Herefordshire, County of"
50,UK,UKG12,Worcestershire
51,UK,UKG13,Warwickshire
52,UK,UKG21,Telford and Wrekin
53,UK,UKG22,Shropshire CC
54,UK,UKG23,Stoke-on-Trent
55,UK,UKG24,Staffordshire CC
56,UK,UKG31,Birmingham
57,UK,UKG32,Solihull
58,UK,UKG33,Coventry
59,UK,UKG36,Dudley
60,UK,UKG37,Sandwell
61,UK,UKG38,Walsall
62,UK,UKG39,Wolverhampton
63,UK,UKH11,Peterborough
64,UK,UKH12,Cambridgeshire CC
65,UK,UKH14,Suffolk
66,UK,UKH15,Norwich and East Norfolk
67,UK,UKH16,North and West Norfolk
68,UK,UKH17,Breckland and South Norfolk
69,UK,UKH21,Luton
70,UK,UKH23,Hertfordshire
71,UK,UKH24,Bedford
72,UK,UKH25,Central Bedfordshire
73,UK,UKH31,Southend-on-Sea
74,UK,UKH32,Thurrock
75,UK,UKH34,Essex Haven Gateway
76,UK,UKH35,West Essex
77,UK,UKH36,Heart of Essex
78,UK,UKH37,Essex Thames Gateway
79,UK,UKI31,Camden and City of London
80,UK,UKI32,Westminster
81,UK,UKI33,Kensington & Chelsea and Hammersmith & Fulham
82,UK,UKI34,Wandsworth
83,UK,UKI41,Hackney and Newham
84,UK,UKI42,Tower Hamlets
85,UK,UKI43,Haringey and Islington
86,UK,UKI44,Lewisham and Southwark
87,UK,UKI45,Lambeth
88,UK,UKI51,Bexley and Greenwich
89,UK,UKI52,Barking & Dagenham and Havering
90,UK,UKI53,Redbridge and Waltham Forest
91,UK,UKI54,Enfield
92,UK,UKI61,Bromley
93,UK,UKI62,Croydon
94,UK,UKI63,"Merton, Kingston upon Thames and Sutton"
95,UK,UKI71,Barnet
96,UK,UKI72,Brent
97,UK,UKI73,Ealing
98,UK,UKI74,Harrow and Hillingdon
99,UK,UKI75,Hounslow and Richmond upon Thames
100,UK,UKJ11,Berkshire
101,UK,UKJ12,Milton Keynes
102,UK,UKJ13,Buckinghamshire CC
103,UK,UKJ14,Oxfordshire
104,UK,UKJ21,Brighton and Hove
105,UK,UKJ22,East Sussex CC
106,UK,UKJ25,West Surrey
107,UK,UKJ26,East Surrey
108,UK,UKJ27,West Sussex (South West)
109,UK,UKJ28,West Sussex (North East)
110,UK,UKJ31,Portsmouth
111,UK,UKJ32,Southampton
112,UK,UKJ34,Isle of Wight
113,UK,UKJ35,South Hampshire
114,UK,UKJ36,Central Hampshire
115,UK,UKJ37,North Hampshire
116,UK,UKJ41,Medway
117,UK,UKJ43,Kent Thames Gateway
118,UK,UKJ44,East Kent
119,UK,UKJ45,Mid Kent
120,UK,UKJ46,West Kent
121,UK,UKK11,"Bristol, City of"
122,UK,UKK12,"Bath and North East Somerset, North Somerset and South Gloucestershire"
123,UK,UKK13,Gloucestershire
124,UK,UKK14,Swindon
125,UK,UKK15,Wiltshire CC
126,UK,UKK21,Bournemouth and Poole
127,UK,UKK22,Dorset CC
128,UK,UKK23,Somerset
129,UK,UKK30,Cornwall and Isles of Scilly
130,UK,UKK41,Plymouth
131,UK,UKK42,Torbay
132,UK,UKK43,Devon CC
133,UK,UKL11,Isle of Anglesey
134,UK,UKL12,Gwynedd
135,UK,UKL13,Conwy and Denbighshire
136,UK,UKL14,South West Wales
137,UK,UKL15,Central Valleys
138,UK,UKL16,Gwent Valleys
139,UK,UKL17,Bridgend and Neath Port Talbot
140,UK,UKL18,Swansea
141,UK,UKL21,Monmouthshire and Newport
142,UK,UKL22,Cardiff and Vale of Glamorgan
143,UK,UKL23,Flintshire and Wrexham
144,UK,UKL24,Powys
145,UK,UKM50,Aberdeen City and Aberdeenshire
146,UK,UKM61,Caithness & Sutherland and Ross & Cromarty
147,UK,UKM62,"Inverness & Nairn and Moray, Badenoch & Strathspey"
148,UK,UKM63,"Lochaber, Skye & Lochalsh, Arran & Cumbrae and Argyll & Bute"
149,UK,UKM64,Na h-Eileanan Siar (Western Isles)
150,UK,UKM65,Orkney Islands
151,UK,UKM66,Shetland Islands
152,UK,UKM71,Angus and Dundee City
153,UK,UKM72,Clackmannanshire and Fife
154,UK,UKM73,East Lothian and Midlothian
155,UK,UKM75,"Edinburgh, City of"
156,UK,UKM76,Falkirk
157,UK,UKM77,Perth & Kinross and Stirling
158,UK,UKM78,West Lothian
159,UK,UKM81,"East Dunbartonshire, West Dunbartonshire and Helensburgh & Lomond"
160,UK,UKM82,Glasgow City
161,UK,UKM83,"Inverclyde, East Renfrewshire and Renfrewshire"
162,UK,UKM84,North Lanarkshire
163,UK,UKM91,Scottish Borders
164,UK,UKM92,Dumfries & Galloway
165,UK,UKM93,East Ayrshire and North Ayrshire mainland
166,UK,UKM94,South Ayrshire
167,UK,UKM95,South Lanarkshire
168,UK,UKN06,Belfast
169,UK,UKN07,"Armagh City, Banbridge and Craigavon"
170,UK,UKN08,"Newry, Mourne and Down"
171,UK,UKN09,Ards and North Down
172,UK,UKN10,Derry City and Strabane
173,UK,UKN11,Mid Ulster
174,UK,UKN12,Causeway Coast and Glens
175,UK,UKN13,Antrim and Newtownabbey
176,UK,UKN14,Lisburn and Castlereagh
177,UK,UKN15,Mid and East Antrim
178,UK,UKN16,Fermanagh and Omagh

 ## Save North Sea NUTS data as csv file

In [43]:
# cp1252 encoding used for latin characters
nuts.to_csv('data/output/NUTS_NS_2016.csv', index=None, encoding="cp1252")

 ## Number of NUTS 1, 2 and 3 territories in the North Sea region (excluding French Overseas Territories)

In [44]:
# number of NUTS 1 territories
len(nuts1)

54

In [45]:
# number of NUTS 2 territories
len(nuts2)

144

In [46]:
# number of NUTS 3 territories
len(nuts3)

810