In [0]:
# Change directory to VSCode workspace root so that relative path loads work correctly. Turn this addition off with the DataScience.changeDirOnImportExport setting
import os
try:
	os.chdir(os.path.join(os.getcwd(), '..'))
	print(os.getcwd())
except:
	pass

 # Nomenclature of territorial units for statistics (NUTS)

In [1]:
# import libraries
import pandas as pd
import numpy as np
pd.set_option('display.max_rows',500) # set up display area to show dataframe
pd.options.display.max_rows # prevent truncation of text strings in columns
pd.set_option('display.max_colwidth',-1)

In [2]:
# read csv files with NUTS data
nuts=pd.read_csv('data/NUTS/NUTS_AT_2016.csv')
nuts.dtypes # return columns and their datatypes

CNTR_CODE    object
NUTS_ID      object
NUTS_NAME    object
dtype: object

 ## North Sea region

In [3]:
# filter for the North Sea region (BE, DE, DK, FR, NL, NO, SE, UK)
nuts=nuts.drop(nuts[~((nuts.CNTR_CODE=='BE')|(nuts.CNTR_CODE=='DE')|(nuts.CNTR_CODE=='DK')|(nuts.CNTR_CODE=='FR')|(nuts.CNTR_CODE=='NL')|(nuts.CNTR_CODE=='NO')|(nuts.CNTR_CODE=='SE')|(nuts.CNTR_CODE=='UK'))].index)

In [4]:
# sort values by NUTS_ID
nuts=nuts.sort_values(by=['NUTS_ID'])

In [5]:
# countries (NUTS 0) - code has two characters
nuts0=nuts.loc[nuts['NUTS_ID'].str.len()==2].copy()
nuts0

     CNTR_CODE NUTS_ID         NUTS_NAME
454   BE        BE      BELGIQUE-BELGIË
1401  DE        DE      DEUTSCHLAND
1242  DK        DK      DANMARK
960   FR        FR      FRANCE
756   NL        NL      NEDERLAND
1823  NO        NO      NORGE
607   SE        SE      SVERIGE
545   UK        UK      UNITED KINGDOM

In [6]:
# number of NUTS 0 territories
len(nuts0)

8

In [7]:
# NUTS 1 - code has three characters
nuts1=nuts.loc[nuts['NUTS_ID'].str.len()==3].copy()

In [8]:
# NUTS 2 - code has four characters
nuts2=nuts.loc[nuts['NUTS_ID'].str.len()==4].copy()

In [9]:
# NUTS 3 - code has five characters
nuts3=nuts.loc[nuts['NUTS_ID'].str.len()==5].copy()

 ## North Sea region - by country

 ### Belgium

In [10]:
# filter for BE
be=nuts.loc[nuts['CNTR_CODE']=='BE'].copy()

In [11]:
# NUTS 1
be_nuts1=be.loc[nuts['NUTS_ID'].str.len()==3].copy()
be_nuts1

,CNTR_CODE,NUTS_ID,NUTS_NAME
453,BE,BE1,RÉGION DE BRUXELLES-CAPITALE/BRUSSELS HOOFDSTEDELIJK GEWEST
1508,BE,BE2,VLAAMS GEWEST
1480,BE,BE3,RÉGION WALLONNE

In [12]:
# number of NUTS 1 territories
len(be_nuts1)

3

In [13]:
# NUTS 2
be_nuts2=be.loc[nuts['NUTS_ID'].str.len()==4].copy()
be_nuts2

,CNTR_CODE,NUTS_ID,NUTS_NAME
452,BE,BE10,Région de Bruxelles-Capitale/ Brussels Hoofdstedelijk Gewest
1507,BE,BE21,Prov. Antwerpen
1503,BE,BE22,Prov. Limburg (BE)
1499,BE,BE23,Prov. Oost-Vlaanderen
1492,BE,BE24,Prov. Vlaams-Brabant
1489,BE,BE25,Prov. West-Vlaanderen
1479,BE,BE31,Prov. Brabant Wallon
1477,BE,BE32,Prov. Hainaut
1469,BE,BE33,Prov. Liège
1463,BE,BE34,Prov. Luxembourg (BE)
1457,BE,BE35,Prov. Namur

In [14]:
# number of NUTS 2 territories
len(be_nuts2)

11

In [15]:
# NUTS 3
be_nuts3=be.loc[nuts['NUTS_ID'].str.len()==5].copy()
be_nuts3

     CNTR_CODE NUTS_ID                                              NUTS_NAME
451   BE        BE100   Arr. de Bruxelles-Capitale/Arr. van Brussel-Hoofdstad
1506  BE        BE211   Arr. Antwerpen
1505  BE        BE212   Arr. Mechelen
1504  BE        BE213   Arr. Turnhout
1502  BE        BE221   Arr. Hasselt
1501  BE        BE222   Arr. Maaseik
1500  BE        BE223   Arr. Tongeren
1498  BE        BE231   Arr. Aalst
1497  BE        BE232   Arr. Dendermonde
1496  BE        BE233   Arr. Eeklo
1495  BE        BE234   Arr. Gent
1494  BE        BE235   Arr. Oudenaarde
1493  BE        BE236   Arr. Sint-Niklaas
1491  BE        BE241   Arr. Halle-Vilvoorde
1490  BE        BE242   Arr. Leuven
1488  BE        BE251   Arr. Brugge
1487  BE        BE252   Arr. Diksmuide
1486  BE        BE253   Arr. Ieper
1485  BE        BE254   Arr. Kortrijk
1484  BE        BE255   Arr. Oostende
1483  BE        BE256   Arr. Roeselare
1482  BE        BE257   Arr. Tielt
1481  BE        BE258   Arr. Veurne
1478  BE        BE310   Arr. Nivelles
1476  BE        BE321   Arr. Ath
1475  BE        BE322   Arr. Charleroi
1474  BE        BE323   Arr. Mons
1473  BE        BE324   Arr. Mouscron
1472  BE        BE325   Arr. Soignies
1471  BE        BE326   Arr. Thuin
1470  BE        BE327   Arr. Tournai
1468  BE        BE331   Arr. Huy
1467  BE        BE332   Arr. Liège
1466  BE        BE334   Arr. Waremme
1465  BE        BE335   Arr. Verviers - communes francophones
1464  BE        BE336   Bezirk Verviers - Deutschsprachige Gemeinschaft
1462  BE        BE341   Arr. Arlon
1461  BE        BE342   Arr. Bastogne
1460  BE        BE343   Arr. Marche-en-Famenne
1459  BE        BE344   Arr. Neufchâteau
1458  BE        BE345   Arr. Virton
1456  BE        BE351   Arr. Dinant
1455  BE        BE352   Arr. Namur
1454  BE        BE353   Arr. Philippeville

In [16]:
# number of NUTS 3 territories
len(be_nuts3)

44

 ### Germany

In [17]:
# filter for DE
de=nuts.loc[nuts['CNTR_CODE']=='DE'].copy()

In [18]:
# NUTS 1
de_nuts1=de.loc[nuts['NUTS_ID'].str.len()==3].copy()
de_nuts1

     CNTR_CODE NUTS_ID               NUTS_NAME
1400  DE        DE1     BADEN-WÜRTTEMBERG
1351  DE        DE2     BAYERN
1747  DE        DE3     BERLIN
1744  DE        DE4     BRANDENBURG
1724  DE        DE5     BREMEN
1720  DE        DE6     HAMBURG
1600  DE        DE7     HESSEN
1570  DE        DE8     MECKLENBURG-VORPOMMERN
1560  DE        DE9     NIEDERSACHSEN
1704  DE        DEA     NORDRHEIN-WESTFALEN
1049  DE        DEB     RHEINLAND-PFALZ
1317  DE        DEC     SAARLAND
1316  DE        DED     SACHSEN
1299  DE        DEE     SACHSEN-ANHALT
1284  DE        DEF     SCHLESWIG-HOLSTEIN
1267  DE        DEG     THÜRINGEN

In [19]:
# number of NUTS 1 territories
len(de_nuts1)

16

In [20]:
# NUTS 2
de_nuts2=de.loc[nuts['NUTS_ID'].str.len()==4].copy()
de_nuts2

     CNTR_CODE NUTS_ID               NUTS_NAME
1399  DE        DE11    Stuttgart
1385  DE        DE12    Karlsruhe
1372  DE        DE13    Freiburg
1361  DE        DE14    Tübingen
1350  DE        DE21    Oberbayern
1326  DE        DE22    Niederbayern
2005  DE        DE23    Oberpfalz
1802  DE        DE24    Oberfranken
1788  DE        DE25    Mittelfranken
1775  DE        DE26    Unterfranken
1762  DE        DE27    Schwaben
1746  DE        DE30    Berlin
1743  DE        DE40    Brandenburg
1723  DE        DE50    Bremen
1719  DE        DE60    Hamburg
1599  DE        DE71    Darmstadt
1584  DE        DE72    Gießen
1578  DE        DE73    Kassel
1569  DE        DE80    Mecklenburg-Vorpommern
1559  DE        DE91    Braunschweig
1549  DE        DE92    Hannover
1541  DE        DE93    Lüneburg
1529  DE        DE94    Weser-Ems
1703  DE        DEA1    Düsseldorf
1091  DE        DEA2    Köln
1079  DE        DEA3    Münster
1070  DE        DEA4    Detmold
1062  DE        DEA5    Arnsberg
1048  DE        DEB1    Koblenz
1038  DE        DEB2    Trier
1032  DE        DEB3    Rheinhessen-Pfalz
1654  DE        DEC0    Saarland
1315  DE        DED2    Dresden
1309  DE        DED4    Chemnitz
1303  DE        DED5    Leipzig
1298  DE        DEE0    Sachsen-Anhalt
1283  DE        DEF0    Schleswig-Holstein
1266  DE        DEG0    Thüringen

In [21]:
# number of NUTS 2 territories
len(de_nuts2)

38

In [22]:
# NUTS 3
de_nuts3=de.loc[nuts['NUTS_ID'].str.len()==5].copy()
de_nuts3

     CNTR_CODE NUTS_ID                                     NUTS_NAME
1398  DE        DE111   Stuttgart, Stadtkreis
1397  DE        DE112   Böblingen
1396  DE        DE113   Esslingen
1395  DE        DE114   Göppingen
1394  DE        DE115   Ludwigsburg
1393  DE        DE116   Rems-Murr-Kreis
1392  DE        DE117   Heilbronn, Stadtkreis
1391  DE        DE118   Heilbronn, Landkreis
1390  DE        DE119   Hohenlohekreis
1389  DE        DE11A   Schwäbisch Hall
1388  DE        DE11B   Main-Tauber-Kreis
1387  DE        DE11C   Heidenheim
1386  DE        DE11D   Ostalbkreis
1384  DE        DE121   Baden-Baden, Stadtkreis
1383  DE        DE122   Karlsruhe, Stadtkreis
1382  DE        DE123   Karlsruhe, Landkreis
1381  DE        DE124   Rastatt
1380  DE        DE125   Heidelberg, Stadtkreis
1379  DE        DE126   Mannheim, Stadtkreis
1378  DE        DE127   Neckar-Odenwald-Kreis
1377  DE        DE128   Rhein-Neckar-Kreis
1376  DE        DE129   Pforzheim, Stadtkreis
1375  DE        DE12A   Calw
1374  DE        DE12B   Enzkreis
1373  DE        DE12C   Freudenstadt
1371  DE        DE131   Freiburg im Breisgau, Stadtkreis
1370  DE        DE132   Breisgau-Hochschwarzwald
1369  DE        DE133   Emmendingen
1368  DE        DE134   Ortenaukreis
1367  DE        DE135   Rottweil
1366  DE        DE136   Schwarzwald-Baar-Kreis
1365  DE        DE137   Tuttlingen
1364  DE        DE138   Konstanz
1363  DE        DE139   Lörrach
1362  DE        DE13A   Waldshut
1360  DE        DE141   Reutlingen
1359  DE        DE142   Tübingen, Landkreis
1358  DE        DE143   Zollernalbkreis
1357  DE        DE144   Ulm, Stadtkreis
1356  DE        DE145   Alb-Donau-Kreis
1355  DE        DE146   Biberach
1354  DE        DE147   Bodenseekreis
1353  DE        DE148   Ravensburg
1352  DE        DE149   Sigmaringen
1349  DE        DE211   Ingolstadt, Kreisfreie Stadt
1348  DE        DE212   München, Kreisfreie Stadt
1347  DE        DE213   Rosenheim, Kreisfreie Stadt
1346  DE        DE214   Altötting
1345  DE        DE215   Berchtesgadener Land
1344  DE        DE216   Bad Tölz-Wolfratshausen
1343  DE        DE217   Dachau
1342  DE        DE218   Ebersberg
1341  DE        DE219   Eichstätt
1340  DE        DE21A   Erding
1339  DE        DE21B   Freising
1338  DE        DE21C   Fürstenfeldbruck
1337  DE        DE21D   Garmisch-Partenkirchen
1336  DE        DE21E   Landsberg am Lech
1335  DE        DE21F   Miesbach
1334  DE        DE21G   Mühldorf a. Inn
1333  DE        DE21H   München, Landkreis
1332  DE        DE21I   Neuburg-Schrobenhausen
1331  DE        DE21J   Pfaffenhofen a. d. Ilm
1330  DE        DE21K   Rosenheim, Landkreis
1329  DE        DE21L   Starnberg
1328  DE        DE21M   Traunstein
1327  DE        DE21N   Weilheim-Schongau
1325  DE        DE221   Landshut, Kreisfreie Stadt
1324  DE        DE222   Passau, Kreisfreie Stadt
2015  DE        DE223   Straubing, Kreisfreie Stadt
2014  DE        DE224   Deggendorf
2013  DE        DE225   Freyung-Grafenau
2012  DE        DE226   Kelheim
2011  DE        DE227   Landshut, Landkreis
2010  DE        DE228   Passau, Landkreis
2009  DE        DE229   Regen
2008  DE        DE22A   Rottal-Inn
2007  DE        DE22B   Straubing-Bogen
2006  DE        DE22C   Dingolfing-Landau
2004  DE        DE231   Amberg, Kreisfreie Stadt
2003  DE        DE232   Regensburg, Kreisfreie Stadt
2002  DE        DE233   Weiden i. d. Opf, Kreisfreie Stadt
2001  DE        DE234   Amberg-Sulzbach
2000  DE        DE235   Cham
1999  DE        DE236   Neumarkt i. d. OPf.
1998  DE        DE237   Neustadt a. d. Waldnaab
1805  DE        DE238   Regensburg, Landkreis
1804  DE        DE239   Schwandorf
1803  DE        DE23A   Tirschenreuth
1801  DE        DE241   Bamberg, Kreisfreie Stadt
1800  DE        DE242   Bayreuth, Kreisfreie Stadt
1799  DE        DE243   Coburg, Kreisfreie Stadt
1798  DE        DE244   Hof, Kreisfreie Stadt
1797  DE        DE245   Bamberg, Landkreis
1796  DE        DE246   Bayreuth, Landkreis
1795  DE        DE247   Coburg, Landkreis
1794  DE        DE248   Forchheim
1793  DE        DE249   Hof, Landkreis
1792  DE        DE24A   Kronach
1791  DE        DE24B   Kulmbach
1790  DE        DE24C   Lichtenfels
1789  DE        DE24D   Wunsiedel i. Fichtelgebirge
1787  DE        DE251   Ansbach, Kreisfreie Stadt
1786  DE        DE252   Erlangen, Kreisfreie Stadt
1785  DE        DE253   Fürth, Kreisfreie Stadt
1784  DE        DE254   Nürnberg, Kreisfreie Stadt
1783  DE        DE255   Schwabach, Kreisfreie Stadt
1782  DE        DE256   Ansbach, Landkreis
1781  DE        DE257   Erlangen-Höchstadt
1780  DE        DE258   Fürth, Landkreis
1779  DE        DE259   Nürnberger Land
1778  DE        DE25A   Neustadt a. d. Aisch-Bad Windsheim
1777  DE        DE25B   Roth
1776  DE        DE25C   Weißenburg-Gunzenhausen
1774  DE        DE261   Aschaffenburg, Kreisfreie Stadt
1773  DE        DE262   Schweinfurt, Kreisfreie Stadt
1772  DE        DE263   Würzburg, Kreisfreie Stadt
1771  DE        DE264   Aschaffenburg, Landkreis
1770  DE        DE265   Bad Kissingen
1769  DE        DE266   Rhön-Grabfeld
1768  DE        DE267   Haßberge
1767  DE        DE268   Kitzingen
1766  DE        DE269   Miltenberg
1765  DE        DE26A   Main-Spessart
1764  DE        DE26B   Schweinfurt, Landkreis
1763  DE        DE26C   Würzburg, Landkreis
1761  DE        DE271   Augsburg, Kreisfreie Stadt
1760  DE        DE272   Kaufbeuren, Kreisfreie Stadt
1759  DE        DE273   Kempten (Allgäu), Kreisfreie Stadt
1758  DE        DE274   Memmingen, Kreisfreie Stadt
1757  DE        DE275   Aichach-Friedberg
1756  DE        DE276   Augsburg, Landkreis
1755  DE        DE277   Dillingen a.d. Donau
1754  DE        DE278   Günzburg
1753  DE        DE279   Neu-Ulm
1752  DE        DE27A   Lindau (Bodensee)
1751  DE        DE27B   Ostallgäu
1750  DE        DE27C   Unterallgäu
1749  DE        DE27D   Donau-Ries
1748  DE        DE27E   Oberallgäu
1745  DE        DE300   Berlin
1742  DE        DE401   Brandenburg an der Havel, Kreisfreie Stadt
1741  DE        DE402   Cottbus, Kreisfreie Stadt
1740  DE        DE403   Frankfurt (Oder), Kreisfreie Stadt
1739  DE        DE404   Potsdam, Kreisfreie Stadt
1738  DE        DE405   Barnim
1737  DE        DE406   Dahme-Spreewald
1736  DE        DE407   Elbe-Elster
1735  DE        DE408   Havelland
1734  DE        DE409   Märkisch-Oderland
1733  DE        DE40A   Oberhavel
1732  DE        DE40B   Oberspreewald-Lausitz
1731  DE        DE40C   Oder-Spree
1730  DE        DE40D   Ostprignitz-Ruppin
1729  DE        DE40E   Potsdam-Mittelmark
1728  DE        DE40F   Prignitz
1727  DE        DE40G   Spree-Neiße
1726  DE        DE40H   Teltow-Fläming
1725  DE        DE40I   Uckermark
1722  DE        DE501   Bremen, Kreisfreie Stadt
1721  DE        DE502   Bremerhaven, Kreisfreie Stadt
657   DE        DE600   Hamburg
1598  DE        DE711   Darmstadt, Kreisfreie Stadt
1597  DE        DE712   Frankfurt am Main, Kreisfreie Stadt
1596  DE        DE713   Offenbach am Main, Kreisfreie Stadt
1595  DE        DE714   Wiesbaden, Kreisfreie Stadt
1594  DE        DE715   Bergstraße
1593  DE        DE716   Darmstadt-Dieburg
1592  DE        DE717   Groß-Gerau
1591  DE        DE718   Hochtaunuskreis
1590  DE        DE719   Main-Kinzig-Kreis
1589  DE        DE71A   Main-Taunus-Kreis
1588  DE        DE71B   Odenwaldkreis
1587  DE        DE71C   Offenbach, Landkreis
1586  DE        DE71D   Rheingau-Taunus-Kreis
1585  DE        DE71E   Wetteraukreis
1583  DE        DE721   Gießen, Landkreis
1582  DE        DE722   Lahn-Dill-Kreis
1581  DE        DE723   Limburg-Weilburg
1580  DE        DE724   Marburg-Biedenkopf
1579  DE        DE725   Vogelsbergkreis
1577  DE        DE731   Kassel, Kreisfreie Stadt
1576  DE        DE732   Fulda
1575  DE        DE733   Hersfeld-Rotenburg
1574  DE        DE734   Kassel, Landkreis
1573  DE        DE735   Schwalm-Eder-Kreis
1572  DE        DE736   Waldeck-Frankenberg
1571  DE        DE737   Werra-Meißner-Kreis
1568  DE        DE803   Rostock, Kreisfreie Stadt
1567  DE        DE804   Schwerin, Kreisfreie Stadt
1566  DE        DE80J   Mecklenburgische Seenplatte
1565  DE        DE80K   Landkreis Rostock
1564  DE        DE80L   Vorpommern-Rügen
1563  DE        DE80M   Nordwestmecklenburg
1562  DE        DE80N   Vorpommern-Greifswald
1561  DE        DE80O   Ludwigslust-Parchim
1558  DE        DE911   Braunschweig, Kreisfreie Stadt
1557  DE        DE912   Salzgitter, Kreisfreie Stadt
1556  DE        DE913   Wolfsburg, Kreisfreie Stadt
1555  DE        DE914   Gifhorn
1554  DE        DE916   Goslar
1553  DE        DE917   Helmstedt
1552  DE        DE918   Northeim
1551  DE        DE91A   Peine
1550  DE        DE91B   Wolfenbüttel
96    DE        DE91C   Göttingen
1548  DE        DE922   Diepholz
1547  DE        DE923   Hameln-Pyrmont
1546  DE        DE925   Hildesheim
1545  DE        DE926   Holzminden
1544  DE        DE927   Nienburg (Weser)
1543  DE        DE928   Schaumburg
1542  DE        DE929   Region Hannover
1540  DE        DE931   Celle
1539  DE        DE932   Cuxhaven
1538  DE        DE933   Harburg
1537  DE        DE934   Lüchow-Dannenberg
1536  DE        DE935   Lüneburg, Landkreis
1535  DE        DE936   Osterholz
1534  DE        DE937   Rotenburg (Wümme)
1533  DE        DE938   Heidekreis
1532  DE        DE939   Stade
1531  DE        DE93A   Uelzen
1530  DE        DE93B   Verden
1528  DE        DE941   Delmenhorst, Kreisfreie Stadt
1527  DE        DE942   Emden, Kreisfreie Stadt
1526  DE        DE943   Oldenburg (Oldenburg), Kreisfreie Stadt
1718  DE        DE944   Osnabrück, Kreisfreie Stadt
1717  DE        DE945   Wilhelmshaven, Kreisfreie Stadt
1716  DE        DE946   Ammerland
1715  DE        DE947   Aurich
1714  DE        DE948   Cloppenburg
1713  DE        DE949   Emsland
1712  DE        DE94A   Friesland (DE)
1711  DE        DE94B   Grafschaft Bentheim
1710  DE        DE94C   Leer
1709  DE        DE94D   Oldenburg, Landkreis
1708  DE        DE94E   Osnabrück, Landkreis
1707  DE        DE94F   Vechta
1706  DE        DE94G   Wesermarsch
1705  DE        DE94H   Wittmund
1702  DE        DEA11   Düsseldorf, Kreisfreie Stadt
1701  DE        DEA12   Duisburg, Kreisfreie Stadt
1103  DE        DEA13   Essen, Kreisfreie Stadt
1102  DE        DEA14   Krefeld, Kreisfreie Stadt
1101  DE        DEA15   Mönchengladbach, Kreisfreie Stadt
437   DE        DEA16   Mülheim an der Ruhr, Kreisfreie Stadt
1100  DE        DEA17   Oberhausen, Kreisfreie Stadt
1099  DE        DEA18   Remscheid, Kreisfreie Stadt
1098  DE        DEA19   Solingen, Kreisfreie Stadt
1097  DE        DEA1A   Wuppertal, Kreisfreie Stadt
1096  DE        DEA1B   Kleve
1095  DE        DEA1C   Mettmann
1094  DE        DEA1D   Rhein-Kreis Neuss
1093  DE        DEA1E   Viersen
1092  DE        DEA1F   Wesel
1090  DE        DEA22   Bonn, Kreisfreie Stadt
1089  DE        DEA23   Köln, Kreisfreie Stadt
1088  DE        DEA24   Leverkusen, Kreisfreie Stadt
1087  DE        DEA26   Düren
1086  DE        DEA27   Rhein-Erft-Kreis
1085  DE        DEA28   Euskirchen
1084  DE        DEA29   Heinsberg
1083  DE        DEA2A   Oberbergischer Kreis
1082  DE        DEA2B   Rheinisch-Bergischer Kreis
1081  DE        DEA2C   Rhein-Sieg-Kreis
1080  DE        DEA2D   Städteregion Aachen
1078  DE        DEA31   Bottrop, Kreisfreie Stadt
1077  DE        DEA32   Gelsenkirchen, Kreisfreie Stadt
1076  DE        DEA33   Münster, Kreisfreie Stadt
1075  DE        DEA34   Borken
1074  DE        DEA35   Coesfeld
1073  DE        DEA36   Recklinghausen
1072  DE        DEA37   Steinfurt
1071  DE        DEA38   Warendorf
1069  DE        DEA41   Bielefeld, Kreisfreie Stadt
1068  DE        DEA42   Gütersloh
1067  DE        DEA43   Herford
1066  DE        DEA44   Höxter
1065  DE        DEA45   Lippe
1064  DE        DEA46   Minden-Lübbecke
1063  DE        DEA47   Paderborn
1061  DE        DEA51   Bochum, Kreisfreie Stadt
1060  DE        DEA52   Dortmund, Kreisfreie Stadt
1059  DE        DEA53   Hagen, Kreisfreie Stadt
1058  DE        DEA54   Hamm, Kreisfreie Stadt
1057  DE        DEA55   Herne, Kreisfreie Stadt
1056  DE        DEA56   Ennepe-Ruhr-Kreis
1055  DE        DEA57   Hochsauerlandkreis
1054  DE        DEA58   Märkischer Kreis
1053  DE        DEA59   Olpe
1052  DE        DEA5A   Siegen-Wittgenstein
1051  DE        DEA5B   Soest
1050  DE        DEA5C   Unna
1047  DE        DEB11   Koblenz, Kreisfreie Stadt
1046  DE        DEB12   Ahrweiler
1045  DE        DEB13   Altenkirchen (Westerwald)
1044  DE        DEB14   Bad Kreuznach
1043  DE        DEB15   Birkenfeld
1042  DE        DEB17   Mayen-Koblenz
1041  DE        DEB18   Neuwied
1040  DE        DEB1A   Rhein-Lahn-Kreis
1039  DE        DEB1B   Westerwaldkreis
97    DE        DEB1C   Cochem-Zell
98    DE        DEB1D   Rhein-Hunsrück-Kreis
1037  DE        DEB21   Trier, Kreisfreie Stadt
1036  DE        DEB22   Bernkastel-Wittlich
1035  DE        DEB23   Eifelkreis Bitburg-Prüm
1034  DE        DEB24   Vulkaneifel
1033  DE        DEB25   Trier-Saarburg
1031  DE        DEB31   Frankenthal (Pfalz), Kreisfreie Stadt
1030  DE        DEB32   Kaiserslautern, Kreisfreie Stadt
1029  DE        DEB33   Landau in der Pfalz, Kreisfreie Stadt
1028  DE        DEB34   Ludwigshafen am Rhein, Kreisfreie Stadt
1027  DE        DEB35   Mainz, Kreisfreie Stadt
1026  DE        DEB36   Neustadt an der Weinstraße, Kreisfreie Stadt
1025  DE        DEB37   Pirmasens, Kreisfreie Stadt
1024  DE        DEB38   Speyer, Kreisfreie Stadt
1023  DE        DEB39   Worms, Kreisfreie Stadt
1022  DE        DEB3A   Zweibrücken, Kreisfreie Stadt
1021  DE        DEB3B   Alzey-Worms
1020  DE        DEB3C   Bad Dürkheim
1019  DE        DEB3D   Donnersbergkreis
1018  DE        DEB3E   Germersheim
1323  DE        DEB3F   Kaiserslautern, Landkreis
1322  DE        DEB3G   Kusel
1321  DE        DEB3H   Südliche Weinstraße
1320  DE        DEB3I   Rhein-Pfalz-Kreis
1319  DE        DEB3J   Mainz-Bingen
1318  DE        DEB3K   Südwestpfalz
1653  DE        DEC01   Regionalverband Saarbrücken
1652  DE        DEC02   Merzig-Wadern
1651  DE        DEC03   Neunkirchen
1650  DE        DEC04   Saarlouis
1649  DE        DEC05   Saarpfalz-Kreis
1648  DE        DEC06   St. Wendel
1314  DE        DED21   Dresden, Kreisfreie Stadt
1313  DE        DED2C   Bautzen
1312  DE        DED2D   Görlitz
1311  DE        DED2E   Meißen
1310  DE        DED2F   Sächsische Schweiz-Osterzgebirge
1308  DE        DED41   Chemnitz, Kreisfreie Stadt
1307  DE        DED42   Erzgebirgskreis
1306  DE        DED43   Mittelsachsen
1305  DE        DED44   Vogtlandkreis
1304  DE        DED45   Zwickau
1302  DE        DED51   Leipzig, Kreisfreie Stadt
1301  DE        DED52   Leipzig
1300  DE        DED53   Nordsachsen
1297  DE        DEE01   Dessau-Roßlau, Kreisfreie Stadt
1296  DE        DEE02   Halle (Saale), Kreisfreie Stadt
1295  DE        DEE03   Magdeburg, Kreisfreie Stadt
1294  DE        DEE04   Altmarkkreis Salzwedel
1293  DE        DEE05   Anhalt-Bitterfeld
1292  DE        DEE06   Jerichower Land
1291  DE        DEE07   Börde
436   DE        DEE08   Burgenlandkreis
1290  DE        DEE09   Harz
1289  DE        DEE0A   Mansfeld-Südharz
1288  DE        DEE0B   Saalekreis
1287  DE        DEE0C   Salzlandkreis
1286  DE        DEE0D   Stendal
1285  DE        DEE0E   Wittenberg
1282  DE        DEF01   Flensburg, Kreisfreie Stadt
1281  DE        DEF02   Kiel, Kreisfreie Stadt
1280  DE        DEF03   Lübeck, Kreisfreie Stadt
1279  DE        DEF04   Neumünster, Kreisfreie Stadt
1278  DE        DEF05   Dithmarschen
1277  DE        DEF06   Herzogtum Lauenburg
1276  DE        DEF07   Nordfriesland
1275  DE        DEF08   Ostholstein
1274  DE        DEF09   Pinneberg
1273  DE        DEF0A   Plön
1272  DE        DEF0B   Rendsburg-Eckernförde
1271  DE        DEF0C   Schleswig-Flensburg
1270  DE        DEF0D   Segeberg
1269  DE        DEF0E   Steinburg
1268  DE        DEF0F   Stormarn
1265  DE        DEG01   Erfurt, Kreisfreie Stadt
1264  DE        DEG02   Gera, Kreisfreie Stadt
1263  DE        DEG03   Jena, Kreisfreie Stadt
1262  DE        DEG04   Suhl, Kreisfreie Stadt
1261  DE        DEG05   Weimar, Kreisfreie Stadt
1260  DE        DEG06   Eichsfeld
1259  DE        DEG07   Nordhausen
1258  DE        DEG09   Unstrut-Hainich-Kreis
1257  DE        DEG0A   Kyffhäuserkreis
1256  DE        DEG0B   Schmalkalden-Meiningen
1255  DE        DEG0C   Gotha
1254  DE        DEG0D   Sömmerda
1253  DE        DEG0E   Hildburghausen
1252  DE        DEG0F   Ilm-Kreis
1251  DE        DEG0G   Weimarer Land
1250  DE        DEG0H   Sonneberg
1249  DE        DEG0I   Saalfeld-Rudolstadt
1248  DE        DEG0J   Saale-Holzland-Kreis
1247  DE        DEG0K   Saale-Orla-Kreis
1246  DE        DEG0L   Greiz
1245  DE        DEG0M   Altenburger Land
1244  DE        DEG0N   Eisenach, Kreisfreie Stadt
1243  DE        DEG0P   Wartburgkreis

In [23]:
# number of NUTS 3 territories
len(de_nuts3)

401

 ### Denmark

In [24]:
# filter for DK
dk=nuts.loc[nuts['CNTR_CODE']=='DK'].copy()

In [25]:
# NUTS 1
dk_nuts1=dk.loc[nuts['NUTS_ID'].str.len()==3].copy()
dk_nuts1

     CNTR_CODE NUTS_ID NUTS_NAME
1241  DK        DK0     DANMARK

In [26]:
# number of NUTS 1 territories
len(dk_nuts1)

1

In [27]:
# NUTS 2
dk_nuts2=dk.loc[nuts['NUTS_ID'].str.len()==4].copy()
dk_nuts2

     CNTR_CODE NUTS_ID    NUTS_NAME
1240  DK        DK01    Hovedstaden
1235  DK        DK02    Sjælland
1232  DK        DK03    Syddanmark
1229  DK        DK04    Midtjylland
1226  DK        DK05    Nordjylland

In [28]:
# number of NUTS 2 territories
len(dk_nuts2)

5

In [29]:
# NUTS 3
dk_nuts3=dk.loc[nuts['NUTS_ID'].str.len()==5].copy()
dk_nuts3

     CNTR_CODE NUTS_ID             NUTS_NAME
1239  DK        DK011   Byen København
1238  DK        DK012   Københavns omegn
1237  DK        DK013   Nordsjælland
1236  DK        DK014   Bornholm
1234  DK        DK021   Østsjælland
1233  DK        DK022   Vest- og Sydsjælland
1231  DK        DK031   Fyn
1230  DK        DK032   Sydjylland
1228  DK        DK041   Vestjylland
1227  DK        DK042   Østjylland
1225  DK        DK050   Nordjylland

In [30]:
# number of NUTS 3 territories
len(dk_nuts3)

11

 ### France

In [31]:
# filter for FR
fr=nuts.loc[nuts['CNTR_CODE']=='FR'].copy()

In [32]:
# NUTS 1
fr_nuts1=fr.loc[nuts['NUTS_ID'].str.len()==3].copy()
fr_nuts1

    CNTR_CODE NUTS_ID                                       NUTS_NAME
424  FR        FR1     ILE-DE-FRANCE
101  FR        FRB     CENTRE - VAL DE LOIRE
109  FR        FRC     BOURGOGNE-FRANCHE-COMTÉ
120  FR        FRD     NORMANDIE
128  FR        FRE     NORD-PAS DE CALAIS-PICARDIE
136  FR        FRF     ALSACE-CHAMPAGNE-ARDENNE-LORRAINE
150  FR        FRG     PAYS DE LA LOIRE
157  FR        FRH     BRETAGNE
163  FR        FRI     AQUITAINE-LIMOUSIN-POITOU-CHARENTES
179  FR        FRJ     LANGUEDOC-ROUSSILLON-MIDI-PYRÉNÉES
195  FR        FRK     AUVERGNE-RHÔNE-ALPES
210  FR        FRL     PROVENCE-ALPES-CÔTE D’AZUR
302  FR        FRM     CORSE
306  FR        FRY     RUP FR - RÉGIONS ULTRAPÉRIPHÉRIQUES FRANÇAISES

In [33]:
# drop entries corresponding to "RUP FR - RÉGIONS ULTRAPÉRIPHÉRIQUES FRANÇAISES" (FRY) - French Overseas Territories
fr=fr[~fr.NUTS_ID.str.contains("FRY")]
nuts=nuts[~nuts.NUTS_ID.str.contains("FRY")]
nuts2=nuts2[~nuts2.NUTS_ID.str.contains("FRY")]
nuts3=nuts3[~nuts3.NUTS_ID.str.contains("FRY")]
fr_nuts1=fr_nuts1[~fr_nuts1.NUTS_ID.str.contains("FRY")]

In [34]:
# number of NUTS 1 territories
len(fr_nuts1)

13

In [35]:
# NUTS 2
fr_nuts2=fr.loc[nuts['NUTS_ID'].str.len()==4].copy()
fr_nuts2

    CNTR_CODE NUTS_ID                   NUTS_NAME
423  FR        FR10    Ile-de-France
102  FR        FRB0    Centre - Val de Loire
110  FR        FRC1    Bourgogne
115  FR        FRC2    Franche-Comté
121  FR        FRD1    Basse-Normandie
125  FR        FRD2    Haute-Normandie
129  FR        FRE1    Nord-Pas de Calais
132  FR        FRE2    Picardie
137  FR        FRF1    Alsace
140  FR        FRF2    Champagne-Ardenne
145  FR        FRF3    Lorraine
151  FR        FRG0    Pays de la Loire
158  FR        FRH0    Bretagne
164  FR        FRI1    Aquitaine
170  FR        FRI2    Limousin
174  FR        FRI3    Poitou-Charentes
180  FR        FRJ1    Languedoc-Roussillon
186  FR        FRJ2    Midi-Pyrénées
196  FR        FRK1    Auvergne
201  FR        FRK2    Rhône-Alpes
211  FR        FRL0    Provence-Alpes-Côte d’Azur
303  FR        FRM0    Corse

In [36]:
# number of NUTS 2 territories
len(fr_nuts2)

22

In [37]:
# NUTS 3
fr_nuts3=fr.loc[nuts['NUTS_ID'].str.len()==5].copy()
fr_nuts3

    CNTR_CODE NUTS_ID                NUTS_NAME
959  FR        FR101   Paris
422  FR        FR102   Seine-et-Marne
421  FR        FR103   Yvelines
958  FR        FR104   Essonne
420  FR        FR105   Hauts-de-Seine
419  FR        FR106   Seine-Saint-Denis
957  FR        FR107   Val-de-Marne
956  FR        FR108   Val-d'Oise
103  FR        FRB01   Cher
104  FR        FRB02   Eure-et-Loir
105  FR        FRB03   Indre
106  FR        FRB04   Indre-et-Loire
107  FR        FRB05   Loir-et-Cher
108  FR        FRB06   Loiret
111  FR        FRC11   Côte-d’Or
112  FR        FRC12   Nièvre
113  FR        FRC13   Saône-et-Loire
114  FR        FRC14   Yonne
116  FR        FRC21   Doubs
117  FR        FRC22   Jura
118  FR        FRC23   Haute-Saône
119  FR        FRC24   Territoire de Belfort
122  FR        FRD11   Calvados
123  FR        FRD12   Manche
124  FR        FRD13   Orne
126  FR        FRD21   Eure
127  FR        FRD22   Seine-Maritime
130  FR        FRE11   Nord
131  FR        FRE12   Pas-de-Calais
133  FR        FRE21   Aisne
134  FR        FRE22   Oise
135  FR        FRE23   Somme
138  FR        FRF11   Bas-Rhin
139  FR        FRF12   Haut-Rhin
141  FR        FRF21   Ardennes
142  FR        FRF22   Aube
143  FR        FRF23   Marne
144  FR        FRF24   Haute-Marne
146  FR        FRF31   Meurthe-et-Moselle
147  FR        FRF32   Meuse
148  FR        FRF33   Moselle
149  FR        FRF34   Vosges
152  FR        FRG01   Loire-Atlantique
153  FR        FRG02   Maine-et-Loire
154  FR        FRG03   Mayenne
155  FR        FRG04   Sarthe
156  FR        FRG05   Vendée
159  FR        FRH01   Côtes-d’Armor
160  FR        FRH02   Finistère
161  FR        FRH03   Ille-et-Vilaine
162  FR        FRH04   Morbihan
165  FR        FRI11   Dordogne
166  FR        FRI12   Gironde
167  FR        FRI13   Landes
168  FR        FRI14   Lot-et-Garonne
169  FR        FRI15   Pyrénées-Atlantiques
171  FR        FRI21   Corrèze
172  FR        FRI22   Creuse
173  FR        FRI23   Haute-Vienne
175  FR        FRI31   Charente
176  FR        FRI32   Charente-Maritime
177  FR        FRI33   Deux-Sèvres
178  FR        FRI34   Vienne
181  FR        FRJ11   Aude
182  FR        FRJ12   Gard
183  FR        FRJ13   Hérault
184  FR        FRJ14   Lozère
185  FR        FRJ15   Pyrénées-Orientales
187  FR        FRJ21   Ariège
188  FR        FRJ22   Aveyron
189  FR        FRJ23   Haute-Garonne
190  FR        FRJ24   Gers
191  FR        FRJ25   Lot
192  FR        FRJ26   Hautes-Pyrénées
193  FR        FRJ27   Tarn
194  FR        FRJ28   Tarn-et-Garonne
197  FR        FRK11   Allier
198  FR        FRK12   Cantal
199  FR        FRK13   Haute-Loire
200  FR        FRK14   Puy-de-Dôme
202  FR        FRK21   Ain
203  FR        FRK22   Ardèche
204  FR        FRK23   Drôme
205  FR        FRK24   Isère
206  FR        FRK25   Loire
207  FR        FRK26   Rhône
208  FR        FRK27   Savoie
209  FR        FRK28   Haute-Savoie
212  FR        FRL01   Alpes-de-Haute-Provence
213  FR        FRL02   Hautes-Alpes
298  FR        FRL03   Alpes-Maritimes
299  FR        FRL04   Bouches-du-Rhône
300  FR        FRL05   Var
301  FR        FRL06   Vaucluse
304  FR        FRM01   Corse-du-Sud
305  FR        FRM02   Haute-Corse

In [38]:
# number of NUTS 3 territories
len(fr_nuts3)

96

 ### Netherlands

In [39]:
# filter for NL
nl=nuts.loc[nuts['CNTR_CODE']=='NL'].copy()

In [40]:
# NUTS 1
nl_nuts1=nl.loc[nuts['NUTS_ID'].str.len()==3].copy()
nl_nuts1

    CNTR_CODE NUTS_ID        NUTS_NAME
755  NL        NL1     NOORD-NEDERLAND
745  NL        NL2     OOST-NEDERLAND
733  NL        NL3     WEST-NEDERLAND
717  NL        NL4     ZUID-NEDERLAND

In [41]:
# number of NUTS 1 territories
len(nl_nuts1)

4

In [42]:
# NUTS 2
nl_nuts2=nl.loc[nuts['NUTS_ID'].str.len()==4].copy()
nl_nuts2

    CNTR_CODE NUTS_ID       NUTS_NAME
754  NL        NL11    Groningen
750  NL        NL12    Friesland (NL)
749  NL        NL13    Drenthe
744  NL        NL21    Overijssel
740  NL        NL22    Gelderland
735  NL        NL23    Flevoland
732  NL        NL31    Utrecht
730  NL        NL32    Noord-Holland
724  NL        NL33    Zuid-Holland
720  NL        NL34    Zeeland
716  NL        NL41    Noord-Brabant
711  NL        NL42    Limburg (NL)

In [43]:
# number of NUTS 2 territories
len(nl_nuts2)

12

In [44]:
# NUTS 3
nl_nuts3=nl.loc[nuts['NUTS_ID'].str.len()==5].copy()
nl_nuts3

    CNTR_CODE NUTS_ID                            NUTS_NAME
753  NL        NL111   Oost-Groningen
752  NL        NL112   Delfzijl en omgeving
751  NL        NL113   Overig Groningen
344  NL        NL124   Noord-Friesland
345  NL        NL125   Zuidwest-Friesland
346  NL        NL126   Zuidoost-Friesland
748  NL        NL131   Noord-Drenthe
747  NL        NL132   Zuidoost-Drenthe
746  NL        NL133   Zuidwest-Drenthe
743  NL        NL211   Noord-Overijssel
742  NL        NL212   Zuidwest-Overijssel
741  NL        NL213   Twente
739  NL        NL221   Veluwe
738  NL        NL224   Zuidwest-Gelderland
737  NL        NL225   Achterhoek
736  NL        NL226   Arnhem/Nijmegen
734  NL        NL230   Flevoland
731  NL        NL310   Utrecht
729  NL        NL321   Kop van Noord-Holland
728  NL        NL323   IJmond
727  NL        NL324   Agglomeratie Haarlem
726  NL        NL325   Zaanstreek
725  NL        NL327   Het Gooi en Vechtstreek
347  NL        NL328   Alkmaar en omgeving
348  NL        NL329   Groot-Amsterdam
405  NL        NL332   Agglomeratie's-Gravenhage
723  NL        NL333   Delft en Westland
722  NL        NL337   Agglomeratie Leiden en Bollenstreek
721  NL        NL33A   Zuidoost-Zuid-Holland
349  NL        NL33B   Oost-Zuid-Holland
350  NL        NL33C   Groot-Rijnmond
719  NL        NL341   Zeeuwsch-Vlaanderen
718  NL        NL342   Overig Zeeland
715  NL        NL411   West-Noord-Brabant
714  NL        NL412   Midden-Noord-Brabant
713  NL        NL413   Noordoost-Noord-Brabant
712  NL        NL414   Zuidoost-Noord-Brabant
710  NL        NL421   Noord-Limburg
709  NL        NL422   Midden-Limburg
708  NL        NL423   Zuid-Limburg

In [45]:
# number of NUTS 3 territories
len(nl_nuts3)

40

 ### Norway

In [46]:
# filter for NO
no=nuts.loc[nuts['CNTR_CODE']=='NO'].copy()

In [47]:
# NUTS 1
no_nuts1=no.loc[nuts['NUTS_ID'].str.len()==3].copy()
no_nuts1

     CNTR_CODE NUTS_ID NUTS_NAME
1852  NO        NO0     NORGE

In [48]:
# number of NUTS 1 territories
len(no_nuts1)

1

In [49]:
# NUTS 2
no_nuts2=no.loc[nuts['NUTS_ID'].str.len()==4].copy()
no_nuts2

     CNTR_CODE NUTS_ID           NUTS_NAME
1816  NO        NO01    Oslo og Akershus
1991  NO        NO02    Hedmark og Oppland
1967  NO        NO03    Sør-Østlandet
1882  NO        NO04    Agder og Rogaland
1942  NO        NO05    Vestlandet
1968  NO        NO06    Trøndelag
1943  NO        NO07    Nord-Norge

In [50]:
# number of NUTS 2 territories
len(no_nuts2)

7

In [51]:
# NUTS 3
no_nuts3=no.loc[nuts['NUTS_ID'].str.len()==5].copy()
no_nuts3

     CNTR_CODE NUTS_ID         NUTS_NAME
1926  NO        NO011   Oslo
1896  NO        NO012   Akershus
1857  NO        NO021   Hedmark
1689  NO        NO022   Oppland
1927  NO        NO031   Østfold
1831  NO        NO032   Buskerud
1858  NO        NO033   Vestfold
1859  NO        NO034   Telemark
1860  NO        NO041   Aust-Agder
1659  NO        NO042   Vest-Agder
1861  NO        NO043   Rogaland
1862  NO        NO051   Hordaland
1897  NO        NO052   Sogn og Fjordane
1928  NO        NO053   Møre og Romsdal
1660  NO        NO060   Trøndelag
1863  NO        NO071   Nordland
1864  NO        NO072   Troms
1955  NO        NO073   Finnmark

In [52]:
# number of NUTS 3 territories
len(no_nuts3)

18

 ### Sweden

In [53]:
# filter for SE
se=nuts.loc[nuts['CNTR_CODE']=='SE'].copy()

In [54]:
# NUTS 1
se_nuts1=se.loc[nuts['NUTS_ID'].str.len()==3].copy()
se_nuts1

    CNTR_CODE NUTS_ID      NUTS_NAME
606  SE        SE1     ÖSTRA SVERIGE
597  SE        SE2     SÖDRA SVERIGE
585  SE        SE3     NORRA SVERIGE

In [55]:
# number of NUTS 1 territories
len(se_nuts1)

3

In [56]:
# NUTS 2
se_nuts2=se.loc[nuts['NUTS_ID'].str.len()==4].copy()
se_nuts2

    CNTR_CODE NUTS_ID            NUTS_NAME
605  SE        SE11    Stockholm
603  SE        SE12    Östra Mellansverige
596  SE        SE21    Småland med öarna
591  SE        SE22    Sydsverige
588  SE        SE23    Västsverige
584  SE        SE31    Norra Mellansverige
580  SE        SE32    Mellersta Norrland
577  SE        SE33    Övre Norrland

In [57]:
# number of NUTS 2 territories
len(se_nuts2)

8

In [58]:
# NUTS 3
se_nuts3=se.loc[nuts['NUTS_ID'].str.len()==5].copy()
se_nuts3

    CNTR_CODE NUTS_ID             NUTS_NAME
604  SE        SE110   Stockholms län
602  SE        SE121   Uppsala län
601  SE        SE122   Södermanlands län
600  SE        SE123   Östergötlands län
599  SE        SE124   Örebro län
598  SE        SE125   Västmanlands län
595  SE        SE211   Jönköpings län
594  SE        SE212   Kronobergs län
593  SE        SE213   Kalmar län
592  SE        SE214   Gotlands län
590  SE        SE221   Blekinge län
589  SE        SE224   Skåne län
587  SE        SE231   Hallands län
586  SE        SE232   Västra Götalands län
583  SE        SE311   Värmlands län
582  SE        SE312   Dalarnas län
581  SE        SE313   Gävleborgs län
579  SE        SE321   Västernorrlands län
578  SE        SE322   Jämtlands län
576  SE        SE331   Västerbottens län
575  SE        SE332   Norrbottens län

In [59]:
# number of NUTS 3 territories
len(se_nuts3)

21

 ### United Kingdom

In [60]:
# filter for UK
uk=nuts.loc[nuts['CNTR_CODE']=='UK'].copy()

In [61]:
# NUTS 1
uk_nuts1=uk.loc[nuts['NUTS_ID'].str.len()==3].copy()
uk_nuts1

    CNTR_CODE NUTS_ID                 NUTS_NAME
544  UK        UKC     NORTH EAST (ENGLAND)
534  UK        UKD     NORTH WEST (ENGLAND)
510  UK        UKE     YORKSHIRE AND THE HUMBER
494  UK        UKF     EAST MIDLANDS (ENGLAND)
479  UK        UKG     WEST MIDLANDS (ENGLAND)
88   UK        UKH     EAST OF ENGLAND
71   UK        UKI     LONDON
55   UK        UKJ     SOUTH EAST (ENGLAND)
29   UK        UKK     SOUTH WEST (ENGLAND)
12   UK        UKL     WALES
466  UK        UKM     SCOTLAND
457  UK        UKN     NORTHERN IRELAND

In [62]:
# number of NUTS 1 territories
len(uk_nuts1)

12

In [63]:
# NUTS 2
uk_nuts2=uk.loc[nuts['NUTS_ID'].str.len()==4].copy()
uk_nuts2

    CNTR_CODE NUTS_ID                                         NUTS_NAME
543  UK        UKC1    Tees Valley and Durham
538  UK        UKC2    Northumberland and Tyne and Wear
533  UK        UKD1    Cumbria
530  UK        UKD3    Greater Manchester
524  UK        UKD4    Lancashire
519  UK        UKD6    Cheshire
515  UK        UKD7    Merseyside
509  UK        UKE1    East Yorkshire and Northern Lincolnshire
505  UK        UKE2    North Yorkshire
502  UK        UKE3    South Yorkshire
499  UK        UKE4    West Yorkshire
493  UK        UKF1    Derbyshire and Nottinghamshire
486  UK        UKF2    Leicestershire, Rutland and Northamptonshire
481  UK        UKF3    Lincolnshire
478  UK        UKG1    Herefordshire, Worcestershire and Warwickshire
474  UK        UKG2    Shropshire and Staffordshire
469  UK        UKG3    West Midlands
87   UK        UKH1    East Anglia
83   UK        UKH2    Bedfordshire and Hertfordshire
78   UK        UKH3    Essex
70   UK        UKI3    Inner London - West
67   UK        UKI4    Inner London - East
64   UK        UKI5    Outer London - East and North East
62   UK        UKI6    Outer London - South
59   UK        UKI7    Outer London - West and North West
54   UK        UKJ1    Berkshire, Buckinghamshire and Oxfordshire
49   UK        UKJ2    Surrey, East and West Sussex
42   UK        UKJ3    Hampshire and Isle of Wight
35   UK        UKJ4    Kent
28   UK        UKK1    Gloucestershire, Wiltshire and Bristol/Bath area
22   UK        UKK2    Dorset and Somerset
18   UK        UKK3    Cornwall and Isles of Scilly
16   UK        UKK4    Devon
11   UK        UKL1    West Wales and The Valleys
2    UK        UKL2    East Wales
465  UK        UKM5    North Eastern Scotland
463  UK        UKM6    Highlands and Islands
388  UK        UKM7    Eastern Scotland
396  UK        UKM8    West Central Scotland
218  UK        UKM9    Southern Scotland
456  UK        UKN0    Northern Ireland

In [64]:
# number of NUTS 2 territories
len(uk_nuts2)

41

In [65]:
# NUTS 3
uk_nuts3=uk.loc[nuts['NUTS_ID'].str.len()==5].copy()
uk_nuts3

,CNTR_CODE,NUTS_ID,NUTS_NAME
542,UK,UKC11,Hartlepool and Stockton-on-Tees
541,UK,UKC12,South Teesside
540,UK,UKC13,Darlington
539,UK,UKC14,Durham CC
537,UK,UKC21,Northumberland
536,UK,UKC22,Tyneside
535,UK,UKC23,Sunderland
532,UK,UKD11,West Cumbria
531,UK,UKD12,East Cumbria
529,UK,UKD33,Manchester
528,UK,UKD34,Greater Manchester South West
527,UK,UKD35,Greater Manchester South East
526,UK,UKD36,Greater Manchester North West
525,UK,UKD37,Greater Manchester North East
523,UK,UKD41,Blackburn with Darwen
522,UK,UKD42,Blackpool
251,UK,UKD44,Lancaster and Wyre
521,UK,UKD45,Mid Lancashire
520,UK,UKD46,East Lancashire
250,UK,UKD47,Chorley and West Lancashire
518,UK,UKD61,Warrington
517,UK,UKD62,Cheshire East
516,UK,UKD63,Cheshire West and Chester
514,UK,UKD71,East Merseyside
513,UK,UKD72,Liverpool
512,UK,UKD73,Sefton
511,UK,UKD74,Wirral
508,UK,UKE11,"Kingston upon Hull, City of"
507,UK,UKE12,East Riding of Yorkshire
506,UK,UKE13,North and North East Lincolnshire
504,UK,UKE21,York
503,UK,UKE22,North Yorkshire CC
501,UK,UKE31,"Barnsley, Doncaster and Rotherham"
500,UK,UKE32,Sheffield
498,UK,UKE41,Bradford
497,UK,UKE42,Leeds
496,UK,UKE44,Calderdale and Kirklees
495,UK,UKE45,Wakefield
492,UK,UKF11,Derby
491,UK,UKF12,East Derbyshire
490,UK,UKF13,South and West Derbyshire
489,UK,UKF14,Nottingham
488,UK,UKF15,North Nottinghamshire
487,UK,UKF16,South Nottinghamshire
485,UK,UKF21,Leicester
484,UK,UKF22,Leicestershire CC and Rutland
483,UK,UKF24,West Northamptonshire
482,UK,UKF25,North Northamptonshire
480,UK,UKF30,Lincolnshire
477,UK,UKG11,"Herefordshire, County of"
476,UK,UKG12,Worcestershire
475,UK,UKG13,Warwickshire
473,UK,UKG21,Telford and Wrekin
472,UK,UKG22,Shropshire CC
471,UK,UKG23,Stoke-on-Trent
470,UK,UKG24,Staffordshire CC
95,UK,UKG31,Birmingham
94,UK,UKG32,Solihull
93,UK,UKG33,Coventry
92,UK,UKG36,Dudley
91,UK,UKG37,Sandwell
90,UK,UKG38,Walsall
89,UK,UKG39,Wolverhampton
86,UK,UKH11,Peterborough
85,UK,UKH12,Cambridgeshire CC
84,UK,UKH14,Suffolk
249,UK,UKH15,Norwich and East Norfolk
248,UK,UKH16,North and West Norfolk
247,UK,UKH17,Breckland and South Norfolk
82,UK,UKH21,Luton
81,UK,UKH23,Hertfordshire
80,UK,UKH24,Bedford
79,UK,UKH25,Central Bedfordshire
77,UK,UKH31,Southend-on-Sea
76,UK,UKH32,Thurrock
75,UK,UKH34,Essex Haven Gateway
74,UK,UKH35,West Essex
73,UK,UKH36,Heart of Essex
72,UK,UKH37,Essex Thames Gateway
246,UK,UKI31,Camden and City of London
69,UK,UKI32,Westminster
245,UK,UKI33,Kensington & Chelsea and Hammersmith & Fulham
68,UK,UKI34,Wandsworth
244,UK,UKI41,Hackney and Newham
66,UK,UKI42,Tower Hamlets
243,UK,UKI43,Haringey and Islington
242,UK,UKI44,Lewisham and Southwark
65,UK,UKI45,Lambeth
241,UK,UKI51,Bexley and Greenwich
240,UK,UKI52,Barking & Dagenham and Havering
239,UK,UKI53,Redbridge and Waltham Forest
63,UK,UKI54,Enfield
61,UK,UKI61,Bromley
60,UK,UKI62,Croydon
238,UK,UKI63,"Merton, Kingston upon Thames and Sutton"
58,UK,UKI71,Barnet
57,UK,UKI72,Brent
56,UK,UKI73,Ealing
237,UK,UKI74,Harrow and Hillingdon
236,UK,UKI75,Hounslow and Richmond upon Thames
53,UK,UKJ11,Berkshire
52,UK,UKJ12,Milton Keynes
51,UK,UKJ13,Buckinghamshire CC
50,UK,UKJ14,Oxfordshire
48,UK,UKJ21,Brighton and Hove
47,UK,UKJ22,East Sussex CC
46,UK,UKJ25,West Surrey
45,UK,UKJ26,East Surrey
44,UK,UKJ27,West Sussex (South West)
43,UK,UKJ28,West Sussex (North East)
41,UK,UKJ31,Portsmouth
40,UK,UKJ32,Southampton
39,UK,UKJ34,Isle of Wight
38,UK,UKJ35,South Hampshire
37,UK,UKJ36,Central Hampshire
36,UK,UKJ37,North Hampshire
34,UK,UKJ41,Medway
33,UK,UKJ43,Kent Thames Gateway
32,UK,UKJ44,East Kent
31,UK,UKJ45,Mid Kent
30,UK,UKJ46,West Kent
27,UK,UKK11,"Bristol, City of"
26,UK,UKK12,"Bath and North East Somerset, North Somerset and South Gloucestershire"
25,UK,UKK13,Gloucestershire
24,UK,UKK14,Swindon
23,UK,UKK15,Wiltshire CC
21,UK,UKK21,Bournemouth and Poole
20,UK,UKK22,Dorset CC
19,UK,UKK23,Somerset
17,UK,UKK30,Cornwall and Isles of Scilly
15,UK,UKK41,Plymouth
14,UK,UKK42,Torbay
13,UK,UKK43,Devon CC
10,UK,UKL11,Isle of Anglesey
9,UK,UKL12,Gwynedd
8,UK,UKL13,Conwy and Denbighshire
7,UK,UKL14,South West Wales
6,UK,UKL15,Central Valleys
5,UK,UKL16,Gwent Valleys
4,UK,UKL17,Bridgend and Neath Port Talbot
3,UK,UKL18,Swansea
1,UK,UKL21,Monmouthshire and Newport
0,UK,UKL22,Cardiff and Vale of Glamorgan
468,UK,UKL23,Flintshire and Wrexham
467,UK,UKL24,Powys
464,UK,UKM50,Aberdeen City and Aberdeenshire
462,UK,UKM61,Caithness & Sutherland and Ross & Cromarty
461,UK,UKM62,"Inverness & Nairn and Moray, Badenoch & Strathspey"
460,UK,UKM63,"Lochaber, Skye & Lochalsh, Arran & Cumbrae and Argyll & Bute"
235,UK,UKM64,Na h-Eileanan Siar (Western Isles)
459,UK,UKM65,Orkney Islands
458,UK,UKM66,Shetland Islands
389,UK,UKM71,Angus and Dundee City
390,UK,UKM72,Clackmannanshire and Fife
391,UK,UKM73,East Lothian and Midlothian
392,UK,UKM75,"Edinburgh, City of"
393,UK,UKM76,Falkirk
394,UK,UKM77,Perth & Kinross and Stirling
395,UK,UKM78,West Lothian
214,UK,UKM81,"East Dunbartonshire, West Dunbartonshire and Helensburgh & Lomond"
215,UK,UKM82,Glasgow City
216,UK,UKM83,"Inverclyde, East Renfrewshire and Renfrewshire"
217,UK,UKM84,North Lanarkshire
219,UK,UKM91,Scottish Borders
220,UK,UKM92,Dumfries & Galloway
221,UK,UKM93,East Ayrshire and North Ayrshire mainland
222,UK,UKM94,South Ayrshire
223,UK,UKM95,South Lanarkshire
224,UK,UKN06,Belfast
225,UK,UKN07,"Armagh City, Banbridge and Craigavon"
226,UK,UKN08,"Newry, Mourne and Down"
227,UK,UKN09,Ards and North Down
228,UK,UKN10,Derry City and Strabane
229,UK,UKN11,Mid Ulster
230,UK,UKN12,Causeway Coast and Glens
231,UK,UKN13,Antrim and Newtownabbey
232,UK,UKN14,Lisburn and Castlereagh
233,UK,UKN15,Mid and East Antrim
234,UK,UKN16,Fermanagh and Omagh

In [66]:
# number of NUTS 3 territories
len(uk_nuts3)

179

 ## Save North Sea NUTS data as csv file

In [67]:
# cp1252 encoding used for latin characters
nuts.to_csv('data/output/NUTS_NS_2016.csv',index=None,encoding="cp1252")

 ## Number of NUTS 1, 2 and 3 territories in the North Sea region (excluding French Overseas Territories)

In [68]:
# number of NUTS 1 territories
len(nuts1)

54

In [69]:
# number of NUTS 2 territories
len(nuts2)

144

In [70]:
# number of NUTS 3 territories
len(nuts3)

810